/* Shared language selector for the portal and product training pages. */
(() => {
  'use strict';

  const languages = [
    ['zh', '中文'],
    ['en', 'English'],
    ['de', 'Deutsch'],
    ['es', 'Español'],
    ['pt', 'Português'],
    ['fr', 'Français'],
    ['it', 'Italiano'],
    ['ru', 'Русский']
  ];
  const codes = new Set(languages.map(([code]) => code));
  const normalize = (value) => codes.has(value) ? value : 'en';

  // These labels are interface copy. Product claims and extracted source text
  // stay in the approved language packs and are not machine-translated here.
  const product = {
    en: {
      trainingHome: 'Training home', storyEyebrow: 'SIX CORE SALES POINTS', productOverview: 'Product overview', overviewButton: 'Back to training menu', overviewTitle: 'Product overview', master: 'MAIN VIEW', stageAria: 'Select a product detail or sales point', dragStageAria: 'Drag the enlarged product view or choose a sales point', emptyKicker: 'START HERE', emptyTitle: 'Choose a sales point.', emptyBody: 'Customer benefit, demo, sales line and proof.', showLabel: 'DEMO', sayLabel: 'SALES LINE', specLabel: 'PROOF', sourcePrefix: 'Source: ', previous: '← Previous point', next: 'Next point →', previousMedia: 'Previous image', nextMedia: 'Next image', closeDetail: 'Back to training menu', closeGallery: 'Close image library', closeFullscreen: 'Close full-screen image', previousImage: 'Previous image', nextImage: 'Next image', openFeature: 'Open', openImage: 'Open high-resolution image:'
    },
    de: {
      trainingHome: 'Trainingsstart', storyEyebrow: 'SECHS VERKAUFSPUNKTE', productOverview: 'Produktübersicht', overviewButton: 'Zurück zum Trainingsmenü', overviewTitle: 'Produktübersicht', master: 'HAUPTANSICHT', stageAria: 'Produktdetail oder Verkaufspunkt wählen', dragStageAria: 'Vergrößerte Produktansicht verschieben oder Verkaufspunkt wählen', emptyKicker: 'HIER STARTEN', emptyTitle: 'Verkaufspunkt wählen.', emptyBody: 'Kundennutzen, Demo, Verkaufsformulierung und Nachweis.', showLabel: 'DEMO', sayLabel: 'VERKAUFSLINIE', specLabel: 'NACHWEIS', sourcePrefix: 'Quelle: ', previous: '← Vorheriger Punkt', next: 'Nächster Punkt →', previousMedia: 'Vorheriges Bild', nextMedia: 'Nächstes Bild', closeDetail: 'Zurück zum Trainingsmenü', closeGallery: 'Bildarchiv schließen', closeFullscreen: 'Vollbild schließen', previousImage: 'Vorheriges Bild', nextImage: 'Nächstes Bild', openFeature: 'Öffnen', openImage: 'Hochauflösendes Bild öffnen:'
    },
    es: {
      trainingHome: 'Inicio de formación', storyEyebrow: 'SEIS PUNTOS DE VENTA', productOverview: 'Vista general', overviewButton: 'Volver al menú', overviewTitle: 'Vista general del producto', master: 'VISTA PRINCIPAL', stageAria: 'Elige un detalle o punto de venta', dragStageAria: 'Arrastra la vista ampliada o elige un punto de venta', emptyKicker: 'EMPIEZA AQUÍ', emptyTitle: 'Elige un punto de venta.', emptyBody: 'Beneficio, demostración, frase comercial y prueba.', showLabel: 'DEMO', sayLabel: 'FRASE COMERCIAL', specLabel: 'PRUEBA', sourcePrefix: 'Fuente: ', previous: '← Punto anterior', next: 'Siguiente punto →', previousMedia: 'Imagen anterior', nextMedia: 'Siguiente imagen', closeDetail: 'Volver al menú', closeGallery: 'Cerrar biblioteca', closeFullscreen: 'Cerrar pantalla completa', previousImage: 'Imagen anterior', nextImage: 'Siguiente imagen', openFeature: 'Abrir', openImage: 'Abrir imagen en alta resolución:'
    },
    pt: {
      trainingHome: 'Início do treinamento', storyEyebrow: 'SEIS PONTOS DE VENDA', productOverview: 'Visão geral', overviewButton: 'Voltar ao menu', overviewTitle: 'Visão geral do produto', master: 'VISTA PRINCIPAL', stageAria: 'Escolha um detalhe ou ponto de venda', dragStageAria: 'Arraste a vista ampliada ou escolha um ponto de venda', emptyKicker: 'COMECE AQUI', emptyTitle: 'Escolha um ponto de venda.', emptyBody: 'Benefício, demonstração, frase comercial e prova.', showLabel: 'DEMO', sayLabel: 'FRASE COMERCIAL', specLabel: 'PROVA', sourcePrefix: 'Fonte: ', previous: '← Ponto anterior', next: 'Próximo ponto →', previousMedia: 'Imagem anterior', nextMedia: 'Próxima imagem', closeDetail: 'Voltar ao menu', closeGallery: 'Fechar biblioteca', closeFullscreen: 'Fechar tela cheia', previousImage: 'Imagem anterior', nextImage: 'Próxima imagem', openFeature: 'Abrir', openImage: 'Abrir imagem em alta resolução:'
    },
    fr: {
      trainingHome: 'Accueil formation', storyEyebrow: 'SIX ARGUMENTS DE VENTE', productOverview: 'Vue d’ensemble', overviewButton: 'Retour au menu', overviewTitle: 'Vue d’ensemble du produit', master: 'VUE PRINCIPALE', stageAria: 'Choisir un détail ou un argument de vente', dragStageAria: 'Déplacer la vue agrandie ou choisir un argument', emptyKicker: 'COMMENCER ICI', emptyTitle: 'Choisir un argument de vente.', emptyBody: 'Bénéfice client, démo, formulation et preuve.', showLabel: 'DÉMO', sayLabel: 'FORMULATION', specLabel: 'PREUVE', sourcePrefix: 'Source : ', previous: '← Argument précédent', next: 'Argument suivant →', previousMedia: 'Image précédente', nextMedia: 'Image suivante', closeDetail: 'Retour au menu', closeGallery: 'Fermer la photothèque', closeFullscreen: 'Fermer le plein écran', previousImage: 'Image précédente', nextImage: 'Image suivante', openFeature: 'Ouvrir', openImage: 'Ouvrir l’image haute résolution :'
    },
    it: {
      trainingHome: 'Home formazione', storyEyebrow: 'SEI PUNTI DI VENDITA', productOverview: 'Panoramica prodotto', overviewButton: 'Torna al menu', overviewTitle: 'Panoramica del prodotto', master: 'VISTA PRINCIPALE', stageAria: 'Scegli un dettaglio o un punto vendita', dragStageAria: 'Trascina la vista ingrandita o scegli un punto vendita', emptyKicker: 'INIZIA QUI', emptyTitle: 'Scegli un punto vendita.', emptyBody: 'Vantaggio, demo, frase commerciale e prova.', showLabel: 'DEMO', sayLabel: 'FRASE COMMERCIALE', specLabel: 'PROVA', sourcePrefix: 'Fonte: ', previous: '← Punto precedente', next: 'Punto successivo →', previousMedia: 'Immagine precedente', nextMedia: 'Immagine successiva', closeDetail: 'Torna al menu', closeGallery: 'Chiudi galleria', closeFullscreen: 'Chiudi schermo intero', previousImage: 'Immagine precedente', nextImage: 'Immagine successiva', openFeature: 'Apri', openImage: 'Apri immagine ad alta risoluzione:'
    },
    ru: {
      trainingHome: 'Главная обучения', storyEyebrow: 'ШЕСТЬ ТОРГОВЫХ АРГУМЕНТОВ', productOverview: 'Обзор продукта', overviewButton: 'Назад в меню', overviewTitle: 'Обзор продукта', master: 'ГЛАВНЫЙ ВИД', stageAria: 'Выберите деталь или торговый аргумент', dragStageAria: 'Перемещайте увеличенный вид или выберите аргумент', emptyKicker: 'НАЧНИТЕ ЗДЕСЬ', emptyTitle: 'Выберите торговый аргумент.', emptyBody: 'Польза, демонстрация, фраза продавца и доказательство.', showLabel: 'ДЕМО', sayLabel: 'ФРАЗА ПРОДАЖИ', specLabel: 'ДОКАЗАТЕЛЬСТВО', sourcePrefix: 'Источник: ', previous: '← Предыдущий пункт', next: 'Следующий пункт →', previousMedia: 'Предыдущее изображение', nextMedia: 'Следующее изображение', closeDetail: 'Назад в меню', closeGallery: 'Закрыть галерею', closeFullscreen: 'Закрыть полный экран', previousImage: 'Предыдущее изображение', nextImage: 'Следующее изображение', openFeature: 'Открыть', openImage: 'Открыть изображение в высоком разрешении:'
    }
  };

  // Shared product-page interface copy. Product claims and source captions stay
  // in the approved language packs; these strings only label the training UI.
  const productExtras = {
    en: { documentTitle: 'Channel Training', languageLabel: 'Choose language', brandKicker: 'MOONDROP · CHANNEL TRAINING', storyHeadline: 'Explore the product.', trainingHubAria: 'Product training menu', storyListAria: 'Product feature stories', interactiveViewAria: 'Interactive product view', focusProgressAria: 'Detail focus progress', featureDetailAria: 'Feature training detail', galleryBoardAria: 'HD image library' },
    de: { documentTitle: 'Vertriebsschulung', languageLabel: 'Sprache wählen', brandKicker: 'MOONDROP · VERTRIEBSSCHULUNG', storyHeadline: 'Produkt entdecken.', galleryKicker: 'MOONDROP · ORIGINALFOTOGRAFIEN', galleryTitle: 'HD-Bildarchiv', galleryIntro: 'Originales Produkt- oder Verpackungsfoto auswählen.', trainingHubAria: 'Produktschulungsmenü', storyListAria: 'Produktmerkmale', interactiveViewAria: 'Interaktive Produktansicht', focusProgressAria: 'Fokusfortschritt', featureDetailAria: 'Details zum Verkaufsargument', galleryBoardAria: 'HD-Bildarchiv' },
    es: { documentTitle: 'Formación comercial', languageLabel: 'Elegir idioma', brandKicker: 'MOONDROP · FORMACIÓN COMERCIAL', storyHeadline: 'Descubre el producto.', galleryKicker: 'MOONDROP · FOTOGRAFÍA ORIGINAL', galleryTitle: 'Biblioteca de imágenes HD', galleryIntro: 'Selecciona una foto original del producto o del embalaje.', trainingHubAria: 'Menú de formación del producto', storyListAria: 'Funciones del producto', interactiveViewAria: 'Vista interactiva del producto', focusProgressAria: 'Progreso del enfoque', featureDetailAria: 'Detalles del argumento de venta', galleryBoardAria: 'Biblioteca de imágenes HD' },
    pt: { documentTitle: 'Treinamento comercial', languageLabel: 'Escolher idioma', brandKicker: 'MOONDROP · TREINAMENTO COMERCIAL', storyHeadline: 'Explore o produto.', galleryKicker: 'MOONDROP · FOTOGRAFIA ORIGINAL', galleryTitle: 'Biblioteca de imagens HD', galleryIntro: 'Selecione uma foto original do produto ou da embalagem.', trainingHubAria: 'Menu de treinamento do produto', storyListAria: 'Recursos do produto', interactiveViewAria: 'Vista interativa do produto', focusProgressAria: 'Progresso do foco', featureDetailAria: 'Detalhes do ponto de venda', galleryBoardAria: 'Biblioteca de imagens HD' },
    fr: { documentTitle: 'Formation réseau', languageLabel: 'Choisir la langue', brandKicker: 'MOONDROP · FORMATION RÉSEAU', storyHeadline: 'Découvrez le produit.', galleryKicker: 'MOONDROP · PHOTOGRAPHIES ORIGINALES', galleryTitle: 'Photothèque HD', galleryIntro: 'Sélectionner une photo originale du produit ou de l’emballage.', trainingHubAria: 'Menu de formation produit', storyListAria: 'Fonctions du produit', interactiveViewAria: 'Vue interactive du produit', focusProgressAria: 'Progression de la mise au point', featureDetailAria: 'Détails de l’argument de vente', galleryBoardAria: 'Photothèque HD' },
    it: { documentTitle: 'Formazione canale', languageLabel: 'Scegli lingua', brandKicker: 'MOONDROP · FORMAZIONE CANALE', storyHeadline: 'Scopri il prodotto.', galleryKicker: 'MOONDROP · FOTOGRAFIE ORIGINALI', galleryTitle: 'Galleria immagini HD', galleryIntro: 'Seleziona una foto originale del prodotto o della confezione.', trainingHubAria: 'Menu formazione prodotto', storyListAria: 'Funzioni del prodotto', interactiveViewAria: 'Vista interattiva del prodotto', focusProgressAria: 'Progresso della messa a fuoco', featureDetailAria: 'Dettagli del punto vendita', galleryBoardAria: 'Galleria immagini HD' },
    ru: { documentTitle: 'Обучение канала', languageLabel: 'Выбрать язык', brandKicker: 'MOONDROP · ОБУЧЕНИЕ КАНАЛА', storyHeadline: 'Изучите продукт.', galleryKicker: 'MOONDROP · ОРИГИНАЛЬНЫЕ ФОТО', galleryTitle: 'HD-галерея', galleryIntro: 'Выберите оригинальную фотографию продукта или упаковки.', trainingHubAria: 'Меню обучения продукта', storyListAria: 'Особенности продукта', interactiveViewAria: 'Интерактивный вид продукта', focusProgressAria: 'Прогресс фокусировки', featureDetailAria: 'Детали торгового аргумента', galleryBoardAria: 'HD-галерея' }
  };
  Object.entries(productExtras).forEach(([code, values]) => Object.assign(product[code], values));

  const portal = {
    en: { sectionClose: 'Back to product training', sections: { core: { tag: 'SELL', title: 'Core Selling Points', subtitle: 'Customer benefit, demo and proof' }, comparison: { tag: 'POSITION', title: 'Product Positioning', subtitle: 'Target user and comparison' }, support: { tag: 'SERVICE', title: 'Package & After-sales', subtitle: 'In the box and warranty' }, reviews: { tag: 'REVIEWS', title: 'Media Reviews', subtitle: 'Verified reviews, direct access' }, gallery: { tag: 'ASSETS', title: 'HD Image Library', subtitle: 'Product and packaging originals' } }, boards: { comparison: { title: 'Product Positioning' }, support: { title: 'Package & After-sales', packageLabel: 'IN THE BOX', packageTitle: 'Standard package contents', warrantyLabel: 'WARRANTY', warrantyTitle: 'Warranty periods', exclusions: 'WHEN SERVICE IS REQUESTED' }, reviews: { title: 'Media Reviews', introTitle: 'Verified reviews, direct access', open: 'Open full review <span class="icon-arrow" aria-hidden="true"></span>' } } },
    de: { sectionClose: 'Zurück zur Produktschulung', sections: { core: { tag: 'VERKAUF', title: 'Verkaufsargumente', subtitle: 'Kundennutzen, Demo und Nachweis' }, comparison: { tag: 'POSITION', title: 'Produktpositionierung', subtitle: 'Zielgruppe und Vergleich' }, support: { tag: 'SERVICE', title: 'Verpackung & Service', subtitle: 'Lieferumfang und Garantie' }, reviews: { tag: 'TESTS', title: 'Medientests', subtitle: 'Verifizierte Tests direkt öffnen' }, gallery: { tag: 'MATERIAL', title: 'HD-Bildarchiv', subtitle: 'Produkt- und Verpackungsoriginale' } }, boards: { comparison: { title: 'Produktpositionierung' }, support: { title: 'Verpackung & Service', packageLabel: 'LIEFERUMFANG', packageTitle: 'Standard-Lieferumfang', warrantyLabel: 'GARANTIE', warrantyTitle: 'Garantiezeiten', exclusions: 'SERVICEANFRAGE' }, reviews: { title: 'Medientests', introTitle: 'Verifizierte Tests direkt öffnen', open: 'Vollständigen Test öffnen <span class="icon-arrow" aria-hidden="true"></span>' } } },
    es: { sectionClose: 'Volver a la formación', sections: { core: { tag: 'VENTA', title: 'Puntos de venta', subtitle: 'Beneficio, demo y prueba' }, comparison: { tag: 'POSICIÓN', title: 'Posicionamiento', subtitle: 'Público y comparación' }, support: { tag: 'SERVICIO', title: 'Embalaje y posventa', subtitle: 'Contenido y garantía' }, reviews: { tag: 'PRUEBAS', title: 'Pruebas de medios', subtitle: 'Pruebas verificadas, acceso directo' }, gallery: { tag: 'RECURSOS', title: 'Biblioteca HD', subtitle: 'Originales de producto y embalaje' } }, boards: { comparison: { title: 'Posicionamiento' }, support: { title: 'Embalaje y posventa', packageLabel: 'EN LA CAJA', packageTitle: 'Contenido estándar', warrantyLabel: 'GARANTÍA', warrantyTitle: 'Plazos de garantía', exclusions: 'SOLICITUD DE SERVICIO' }, reviews: { title: 'Pruebas de medios', introTitle: 'Pruebas verificadas, acceso directo', open: 'Abrir prueba completa <span class="icon-arrow" aria-hidden="true"></span>' } } },
    pt: { sectionClose: 'Voltar ao treinamento', sections: { core: { tag: 'VENDA', title: 'Pontos de venda', subtitle: 'Benefício, demo e prova' }, comparison: { tag: 'POSIÇÃO', title: 'Posicionamento', subtitle: 'Público e comparação' }, support: { tag: 'SERVIÇO', title: 'Embalagem e pós-venda', subtitle: 'Conteúdo e garantia' }, reviews: { tag: 'TESTES', title: 'Avaliações de mídia', subtitle: 'Avaliações verificadas, acesso direto' }, gallery: { tag: 'RECURSOS', title: 'Biblioteca HD', subtitle: 'Originais do produto e da embalagem' } }, boards: { comparison: { title: 'Posicionamento' }, support: { title: 'Embalagem e pós-venda', packageLabel: 'NA CAIXA', packageTitle: 'Conteúdo padrão', warrantyLabel: 'GARANTIA', warrantyTitle: 'Prazos de garantia', exclusions: 'SOLICITAÇÃO DE SERVIÇO' }, reviews: { title: 'Avaliações de mídia', introTitle: 'Avaliações verificadas, acesso direto', open: 'Abrir avaliação completa <span class="icon-arrow" aria-hidden="true"></span>' } } },
    fr: { sectionClose: 'Retour à la formation', sections: { core: { tag: 'VENTE', title: 'Arguments de vente', subtitle: 'Bénéfice, démo et preuve' }, comparison: { tag: 'POSITION', title: 'Positionnement produit', subtitle: 'Public cible et comparaison' }, support: { tag: 'SERVICE', title: 'Emballage & après-vente', subtitle: 'Contenu et garantie' }, reviews: { tag: 'TESTS', title: 'Tests médias', subtitle: 'Tests vérifiés, accès direct' }, gallery: { tag: 'RESSOURCES', title: 'Photothèque HD', subtitle: 'Originaux produit et emballage' } }, boards: { comparison: { title: 'Positionnement produit' }, support: { title: 'Emballage & après-vente', packageLabel: 'DANS LA BOÎTE', packageTitle: 'Contenu standard', warrantyLabel: 'GARANTIE', warrantyTitle: 'Durées de garantie', exclusions: 'DEMANDE DE SERVICE' }, reviews: { title: 'Tests médias', introTitle: 'Tests vérifiés, accès direct', open: 'Ouvrir le test complet <span class="icon-arrow" aria-hidden="true"></span>' } } },
    it: { sectionClose: 'Torna alla formazione', sections: { core: { tag: 'VENDITA', title: 'Punti di vendita', subtitle: 'Vantaggio, demo e prova' }, comparison: { tag: 'POSIZIONE', title: 'Posizionamento prodotto', subtitle: 'Pubblico e confronto' }, support: { tag: 'SERVIZIO', title: 'Confezione e assistenza', subtitle: 'Contenuto e garanzia' }, reviews: { tag: 'TEST', title: 'Test dei media', subtitle: 'Test verificati, accesso diretto' }, gallery: { tag: 'RISORSE', title: 'Galleria HD', subtitle: 'Originali del prodotto e della confezione' } }, boards: { comparison: { title: 'Posizionamento prodotto' }, support: { title: 'Confezione e assistenza', packageLabel: 'CONTENUTO', packageTitle: 'Dotazione standard', warrantyLabel: 'GARANZIA', warrantyTitle: 'Durata della garanzia', exclusions: 'RICHIESTA DI ASSISTENZA' }, reviews: { title: 'Test dei media', introTitle: 'Test verificati, accesso diretto', open: 'Apri il test completo <span class="icon-arrow" aria-hidden="true"></span>' } } },
    ru: { sectionClose: 'Назад к обучению', sections: { core: { tag: 'ПРОДАЖА', title: 'Торговые аргументы', subtitle: 'Польза, демо и доказательство' }, comparison: { tag: 'ПОЗИЦИЯ', title: 'Позиционирование', subtitle: 'Целевая аудитория и сравнение' }, support: { tag: 'СЕРВИС', title: 'Комплектация и сервис', subtitle: 'Комплект и гарантия' }, reviews: { tag: 'ОБЗОРЫ', title: 'Медиаобзоры', subtitle: 'Проверенные обзоры, прямой доступ' }, gallery: { tag: 'МАТЕРИАЛЫ', title: 'HD-галерея', subtitle: 'Оригиналы продукта и упаковки' } }, boards: { comparison: { title: 'Позиционирование' }, support: { title: 'Комплектация и сервис', packageLabel: 'В КОРОБКЕ', packageTitle: 'Стандартная комплектация', warrantyLabel: 'ГАРАНТИЯ', warrantyTitle: 'Срок гарантии', exclusions: 'ЗАПРОС НА СЕРВИС' }, reviews: { title: 'Медиаобзоры', introTitle: 'Проверенные обзоры, прямой доступ', open: 'Открыть полный обзор <span class="icon-arrow" aria-hidden="true"></span>' } } }
  };

  const mobile = {
    de: { 'Continue reading': 'Weiterlesen', 'Choose a selling point': 'Verkaufspunkt wählen', 'Training menu': 'Trainingsmenü', 'Product overview': 'Produktübersicht', 'Product training home': 'Produktschulung', 'Close menu': 'Menü schließen', 'Zoom in': 'Vergrößern', 'Reset': 'Zurücksetzen', 'Full-size image': 'Bild in voller Größe', 'Previous image': 'Vorheriges Bild', 'Next image': 'Nächstes Bild', 'Close image': 'Bild schließen', 'Selling-point navigation': 'Verkaufsnavigation', 'Product photograph, automatically focused on the selected selling point': 'Produktfotografie, automatisch auf den Verkaufspunkt fokussiert', '← Previous': '← Zurück', 'Overview': 'Übersicht', 'Contents': 'Inhalt', '← Previous': '← Zurück', 'Start →': 'Start →', 'Next →': 'Weiter →', 'Back to category': 'Zur Kategorie', 'Back to product training': 'Zur Produktschulung', 'Open training menu': 'Trainingsmenü öffnen', 'Full product': 'Gesamtansicht' },
    es: { 'Continue reading': 'Continuar leyendo', 'Choose a selling point': 'Elegir punto de venta', 'Training menu': 'Menú de formación', 'Product overview': 'Vista general', 'Product training home': 'Inicio de formación', 'Close menu': 'Cerrar menú', 'Zoom in': 'Ampliar', 'Reset': 'Restablecer', 'Full-size image': 'Imagen a tamaño completo', 'Previous image': 'Imagen anterior', 'Next image': 'Siguiente imagen', 'Close image': 'Cerrar imagen', 'Selling-point navigation': 'Navegación de ventas', 'Product photograph, automatically focused on the selected selling point': 'Foto del producto, enfocada automáticamente en el punto de venta', '← Previous': '← Anterior', 'Overview': 'Vista general', 'Contents': 'Contenido', 'Start →': 'Empezar →', 'Next →': 'Siguiente →', 'Back to category': 'Volver a la categoría', 'Back to product training': 'Volver a la formación', 'Open training menu': 'Abrir menú de formación', 'Full product': 'Producto completo' },
    pt: { 'Continue reading': 'Continuar leitura', 'Choose a selling point': 'Escolha um ponto de venda', 'Training menu': 'Menu de treinamento', 'Product overview': 'Visão geral', 'Product training home': 'Início do treinamento', 'Close menu': 'Fechar menu', 'Zoom in': 'Ampliar', 'Reset': 'Redefinir', 'Full-size image': 'Imagem em tamanho real', 'Previous image': 'Imagem anterior', 'Next image': 'Próxima imagem', 'Close image': 'Fechar imagem', 'Selling-point navigation': 'Navegação de vendas', 'Product photograph, automatically focused on the selected selling point': 'Foto do produto focada automaticamente no ponto de venda', '← Previous': '← Anterior', 'Overview': 'Visão geral', 'Contents': 'Conteúdo', 'Start →': 'Começar →', 'Next →': 'Próximo →', 'Back to category': 'Voltar à categoria', 'Back to product training': 'Voltar ao treinamento', 'Open training menu': 'Abrir menu de treinamento', 'Full product': 'Produto completo' },
    fr: { 'Continue reading': 'Reprendre la lecture', 'Choose a selling point': 'Choisir un argument', 'Training menu': 'Menu de formation', 'Product overview': 'Vue d’ensemble', 'Product training home': 'Accueil formation', 'Close menu': 'Fermer le menu', 'Zoom in': 'Agrandir', 'Reset': 'Réinitialiser', 'Full-size image': 'Image plein format', 'Previous image': 'Image précédente', 'Next image': 'Image suivante', 'Close image': 'Fermer l’image', 'Selling-point navigation': 'Navigation commerciale', 'Product photograph, automatically focused on the selected selling point': 'Photo du produit, focalisée sur l’argument choisi', '← Previous': '← Précédent', 'Overview': 'Vue d’ensemble', 'Contents': 'Contenu', 'Start →': 'Commencer →', 'Next →': 'Suivant →', 'Back to category': 'Retour à la catégorie', 'Back to product training': 'Retour à la formation', 'Open training menu': 'Ouvrir le menu de formation', 'Full product': 'Produit complet' },
    it: { 'Continue reading': 'Continua lettura', 'Choose a selling point': 'Scegli un punto di vendita', 'Training menu': 'Menu formazione', 'Product overview': 'Panoramica prodotto', 'Product training home': 'Home formazione', 'Close menu': 'Chiudi menu', 'Zoom in': 'Ingrandisci', 'Reset': 'Ripristina', 'Full-size image': 'Immagine a dimensione intera', 'Previous image': 'Immagine precedente', 'Next image': 'Immagine successiva', 'Close image': 'Chiudi immagine', 'Selling-point navigation': 'Navigazione vendita', 'Product photograph, automatically focused on the selected selling point': 'Foto del prodotto focalizzata sul punto di vendita scelto', '← Previous': '← Precedente', 'Overview': 'Panoramica', 'Contents': 'Contenuti', 'Start →': 'Inizia →', 'Next →': 'Successivo →', 'Back to category': 'Torna alla categoria', 'Back to product training': 'Torna alla formazione', 'Open training menu': 'Apri menu formazione', 'Full product': 'Prodotto completo' },
    ru: { 'Continue reading': 'Продолжить чтение', 'Choose a selling point': 'Выберите торговый аргумент', 'Training menu': 'Меню обучения', 'Product overview': 'Обзор продукта', 'Product training home': 'Главная обучения', 'Close menu': 'Закрыть меню', 'Zoom in': 'Увеличить', 'Reset': 'Сбросить', 'Full-size image': 'Изображение в полном размере', 'Previous image': 'Предыдущее изображение', 'Next image': 'Следующее изображение', 'Close image': 'Закрыть изображение', 'Selling-point navigation': 'Навигация по аргументам', 'Product photograph, automatically focused on the selected selling point': 'Фото продукта с фокусом на выбранном аргументе', '← Previous': '← Назад', 'Overview': 'Обзор', 'Contents': 'Содержание', 'Start →': 'Начать →', 'Next →': 'Далее →', 'Back to category': 'Назад к категории', 'Back to product training': 'Назад к обучению', 'Open training menu': 'Открыть меню обучения', 'Full product': 'Полный вид продукта' }
  };

  const compact = {
    en: { home: 'Training home', language: 'Choose language', hubMenuKicker: 'CHOOSE A TOPIC', core: 'Core Selling Points', coreSub: 'Customer benefit, demo and proof', positioning: 'Product Positioning', positioningSub: 'Target user and comparison', support: 'Package & After-sales', supportSub: 'In the box and warranty', reviews: 'Media Reviews', reviewsSub: 'Verified reviews, direct access', gallery: 'HD Image Library', gallerySub: 'Product and packaging originals', railKicker: 'SIX CORE SALES POINTS', overview: 'Overview', back: 'Back to training', viewerOverview: 'Product overview', mainView: 'MAIN VIEW', stageOverview: 'MAIN VIEW / HD', emptyKicker: 'START HERE', emptyTitle: 'Choose a sales point.', emptyBody: 'Customer benefit, demo, sales line and proof.', closeFeature: 'Close feature details', show: 'DEMO', say: 'SALES LINE', spec: 'PROOF', previous: 'Previous point', next: 'Next point', closeSection: 'Back to training', openReview: 'Open full review <span class="icon-arrow" aria-hidden="true"></span>', galleryNote: 'Select an image to inspect the original.' },
    de: { home: 'Trainingsstart', language: 'Sprache wählen', hubMenuKicker: 'THEMA WÄHLEN', core: 'Verkaufsargumente', coreSub: 'Kundennutzen, Demo und Nachweis', positioning: 'Produktpositionierung', positioningSub: 'Zielgruppe und Vergleich', support: 'Verpackung & Service', supportSub: 'Lieferumfang und Garantie', reviews: 'Medientests', reviewsSub: 'Verifizierte Tests direkt öffnen', gallery: 'HD-Bildarchiv', gallerySub: 'Produkt- und Verpackungsoriginale', railKicker: 'SECHS VERKAUFSPUNKTE', overview: 'Übersicht', back: 'Zurück zur Schulung', viewerOverview: 'Produktübersicht', mainView: 'HAUPTANSICHT', stageOverview: 'HAUPTANSICHT / HD', emptyKicker: 'HIER STARTEN', emptyTitle: 'Verkaufspunkt wählen.', emptyBody: 'Kundennutzen, Demo, Verkaufsformulierung und Nachweis.', closeFeature: 'Details schließen', show: 'DEMO', say: 'VERKAUFSLINIE', spec: 'NACHWEIS', previous: 'Vorheriger Punkt', next: 'Nächster Punkt', closeSection: 'Zurück zur Schulung', openReview: 'Vollständigen Test öffnen <span class="icon-arrow" aria-hidden="true"></span>', galleryNote: 'Originalbild auswählen.' },
    es: { home: 'Inicio de formación', language: 'Elegir idioma', hubMenuKicker: 'ELIGE UN TEMA', core: 'Puntos de venta', coreSub: 'Beneficio, demo y prueba', positioning: 'Posicionamiento', positioningSub: 'Público y comparación', support: 'Embalaje y posventa', supportSub: 'Contenido y garantía', reviews: 'Pruebas de medios', reviewsSub: 'Pruebas verificadas, acceso directo', gallery: 'Biblioteca HD', gallerySub: 'Originales de producto y embalaje', railKicker: 'SEIS PUNTOS DE VENTA', overview: 'Vista general', back: 'Volver a la formación', viewerOverview: 'Vista general del producto', mainView: 'VISTA PRINCIPAL', stageOverview: 'VISTA PRINCIPAL / HD', emptyKicker: 'EMPIEZA AQUÍ', emptyTitle: 'Elige un punto de venta.', emptyBody: 'Beneficio, demo, frase comercial y prueba.', closeFeature: 'Cerrar detalles', show: 'DEMO', say: 'FRASE COMERCIAL', spec: 'PRUEBA', previous: 'Punto anterior', next: 'Siguiente punto', closeSection: 'Volver a la formación', openReview: 'Abrir prueba completa <span class="icon-arrow" aria-hidden="true"></span>', galleryNote: 'Selecciona una imagen original.' },
    pt: { home: 'Início do treinamento', language: 'Escolher idioma', hubMenuKicker: 'ESCOLHA UM TEMA', core: 'Pontos de venda', coreSub: 'Benefício, demo e prova', positioning: 'Posicionamento', positioningSub: 'Público e comparação', support: 'Embalagem e pós-venda', supportSub: 'Conteúdo e garantia', reviews: 'Avaliações de mídia', reviewsSub: 'Avaliações verificadas, acesso direto', gallery: 'Biblioteca HD', gallerySub: 'Originais do produto e da embalagem', railKicker: 'SEIS PONTOS DE VENDA', overview: 'Visão geral', back: 'Voltar ao treinamento', viewerOverview: 'Visão geral do produto', mainView: 'VISTA PRINCIPAL', stageOverview: 'VISTA PRINCIPAL / HD', emptyKicker: 'COMECE AQUI', emptyTitle: 'Escolha um ponto de venda.', emptyBody: 'Benefício, demo, frase comercial e prova.', closeFeature: 'Fechar detalhes', show: 'DEMO', say: 'FRASE COMERCIAL', spec: 'PROVA', previous: 'Ponto anterior', next: 'Próximo ponto', closeSection: 'Voltar ao treinamento', openReview: 'Abrir avaliação completa <span class="icon-arrow" aria-hidden="true"></span>', galleryNote: 'Selecione uma imagem original.' },
    fr: { home: 'Accueil formation', language: 'Choisir la langue', hubMenuKicker: 'CHOISIR UN THÈME', core: 'Arguments de vente', coreSub: 'Bénéfice, démo et preuve', positioning: 'Positionnement produit', positioningSub: 'Public cible et comparaison', support: 'Emballage & après-vente', supportSub: 'Contenu et garantie', reviews: 'Tests médias', reviewsSub: 'Tests vérifiés, accès direct', gallery: 'Photothèque HD', gallerySub: 'Originaux produit et emballage', railKicker: 'SIX ARGUMENTS DE VENTE', overview: 'Vue d’ensemble', back: 'Retour à la formation', viewerOverview: 'Vue d’ensemble du produit', mainView: 'VUE PRINCIPALE', stageOverview: 'VUE PRINCIPALE / HD', emptyKicker: 'COMMENCER ICI', emptyTitle: 'Choisir un argument.', emptyBody: 'Bénéfice, démo, formulation et preuve.', closeFeature: 'Fermer les détails', show: 'DÉMO', say: 'FORMULATION', spec: 'PREUVE', previous: 'Argument précédent', next: 'Argument suivant', closeSection: 'Retour à la formation', openReview: 'Ouvrir le test complet <span class="icon-arrow" aria-hidden="true"></span>', galleryNote: 'Sélectionner un original.' },
    it: { home: 'Home formazione', language: 'Scegli lingua', hubMenuKicker: 'SCEGLI UN TEMA', core: 'Punti di vendita', coreSub: 'Vantaggio, demo e prova', positioning: 'Posizionamento prodotto', positioningSub: 'Pubblico e confronto', support: 'Confezione e assistenza', supportSub: 'Contenuto e garanzia', reviews: 'Test dei media', reviewsSub: 'Test verificati, accesso diretto', gallery: 'Galleria HD', gallerySub: 'Originali del prodotto e della confezione', railKicker: 'SEI PUNTI DI VENDITA', overview: 'Panoramica', back: 'Torna alla formazione', viewerOverview: 'Panoramica del prodotto', mainView: 'VISTA PRINCIPALE', stageOverview: 'VISTA PRINCIPALE / HD', emptyKicker: 'INIZIA QUI', emptyTitle: 'Scegli un punto di vendita.', emptyBody: 'Vantaggio, demo, frase commerciale e prova.', closeFeature: 'Chiudi dettagli', show: 'DEMO', say: 'FRASE COMMERCIALE', spec: 'PROVA', previous: 'Punto precedente', next: 'Punto successivo', closeSection: 'Torna alla formazione', openReview: 'Apri il test completo <span class="icon-arrow" aria-hidden="true"></span>', galleryNote: 'Seleziona un originale.' },
    ru: { home: 'Главная обучения', language: 'Выбрать язык', hubMenuKicker: 'ВЫБЕРИТЕ ТЕМУ', core: 'Торговые аргументы', coreSub: 'Польза, демо и доказательство', positioning: 'Позиционирование', positioningSub: 'Целевая аудитория и сравнение', support: 'Комплектация и сервис', supportSub: 'Комплект и гарантия', reviews: 'Медиаобзоры', reviewsSub: 'Проверенные обзоры, прямой доступ', gallery: 'HD-галерея', gallerySub: 'Оригиналы продукта и упаковки', railKicker: 'ШЕСТЬ ТОРГОВЫХ АРГУМЕНТОВ', overview: 'Обзор', back: 'Назад к обучению', viewerOverview: 'Обзор продукта', mainView: 'ГЛАВНЫЙ ВИД', stageOverview: 'ГЛАВНЫЙ ВИД / HD', emptyKicker: 'НАЧНИТЕ ЗДЕСЬ', emptyTitle: 'Выберите торговый аргумент.', emptyBody: 'Польза, демо, фраза продавца и доказательство.', closeFeature: 'Закрыть детали', show: 'ДЕМО', say: 'ФРАЗА ПРОДАЖИ', spec: 'ДОКАЗАТЕЛЬСТВО', previous: 'Предыдущий пункт', next: 'Следующий пункт', closeSection: 'Назад к обучению', openReview: 'Открыть полный обзор <span class="icon-arrow" aria-hidden="true"></span>', galleryNote: 'Выберите оригинал изображения.' }
  };

  const compactExtras = {
    de: { railTitle: '<span>Produkt entdecken.</span><br><span>Argumente lernen.</span>', viewerSubtitle: 'Hauptansicht · Produktdetails', stageSub: 'PRODUKTANSICHT · FUNKTIONSGUIDE', stageAria: 'Produktdetail oder Verkaufspunkt wählen', dragStageAria: 'Vergrößerte Produktansicht verschieben oder Verkaufspunkt wählen', overviewNote: 'Produktübersicht', trainingHubAria: 'Produktschulungsmenü', storyListAria: 'Produktmerkmale', interactiveViewAria: 'Interaktive Produktansicht', focusProgressAria: 'Fokusfortschritt', featureDetailAria: 'Details zum Verkaufsargument', galleryBoardAria: 'HD-Bildarchiv', galleryKicker: 'MOONDROP · ORIGINALFOTOGRAFIEN', galleryTitle: 'HD-Bildarchiv', galleryIntro: 'Originales Produkt- oder Verpackungsfoto auswählen.', galleryHeading: 'HD-Produktbibliothek', galleryDescription: 'Produkt-, Trage- und Verpackungsdetails für Kundendemonstrationen.', reviewIntroTitle: 'Verifizierte Tests direkt öffnen', inBox: 'LIEFERUMFANG', warranty: 'GARANTIE', supportKicker: 'VERPACKUNG & GARANTIE', coreTag: 'VERKAUF', positioningTag: 'POSITION', supportTag: 'SERVICE', reviewsTag: 'TESTS', galleryTag: 'MATERIAL' },
    es: { railTitle: '<span>Descubre el producto.</span><br><span>Domina la venta.</span>', viewerSubtitle: 'Vista principal · Detalles del producto', stageSub: 'VISTA DEL PRODUCTO · GUÍA DE FUNCIONES', stageAria: 'Elige un detalle o punto de venta', dragStageAria: 'Arrastra la vista ampliada o elige un punto de venta', overviewNote: 'Vista general del producto', trainingHubAria: 'Menú de formación del producto', storyListAria: 'Funciones del producto', interactiveViewAria: 'Vista interactiva del producto', focusProgressAria: 'Progreso del enfoque', featureDetailAria: 'Detalles del argumento de venta', galleryBoardAria: 'Biblioteca de imágenes HD', galleryKicker: 'MOONDROP · FOTOGRAFÍA ORIGINAL', galleryTitle: 'Biblioteca de imágenes HD', galleryIntro: 'Selecciona una foto original del producto o del embalaje.', galleryHeading: 'Biblioteca de producto HD', galleryDescription: 'Detalles de producto, uso y embalaje para demostraciones.', reviewIntroTitle: 'Pruebas verificadas, acceso directo', inBox: 'EN LA CAJA', warranty: 'GARANTÍA', supportKicker: 'EMBALAJE Y GARANTÍA', coreTag: 'VENTA', positioningTag: 'POSICIÓN', supportTag: 'SERVICIO', reviewsTag: 'PRUEBAS', galleryTag: 'RECURSOS' },
    pt: { railTitle: '<span>Explore o produto.</span><br><span>Domine a venda.</span>', viewerSubtitle: 'Vista principal · Detalhes do produto', stageSub: 'VISTA DO PRODUTO · GUIA DE FUNÇÕES', stageAria: 'Escolha um detalhe ou ponto de venda', dragStageAria: 'Arraste a vista ampliada ou escolha um ponto de venda', overviewNote: 'Visão geral do produto', trainingHubAria: 'Menu de treinamento do produto', storyListAria: 'Recursos do produto', interactiveViewAria: 'Vista interativa do produto', focusProgressAria: 'Progresso do foco', featureDetailAria: 'Detalhes do ponto de venda', galleryBoardAria: 'Biblioteca de imagens HD', galleryKicker: 'MOONDROP · FOTOGRAFIA ORIGINAL', galleryTitle: 'Biblioteca de imagens HD', galleryIntro: 'Selecione uma foto original do produto ou da embalagem.', galleryHeading: 'Biblioteca de produto HD', galleryDescription: 'Detalhes do produto, uso e embalagem para demonstrações.', reviewIntroTitle: 'Avaliações verificadas, acesso direto', inBox: 'NA CAIXA', warranty: 'GARANTIA', supportKicker: 'EMBALAGEM E GARANTIA', coreTag: 'VENDA', positioningTag: 'POSIÇÃO', supportTag: 'SERVIÇO', reviewsTag: 'TESTES', galleryTag: 'RECURSOS' },
    fr: { railTitle: '<span>Découvrez le produit.</span><br><span>Maîtrisez la vente.</span>', viewerSubtitle: 'Vue principale · Détails du produit', stageSub: 'VUE PRODUIT · GUIDE DES FONCTIONS', stageAria: 'Choisir un détail ou un argument de vente', dragStageAria: 'Déplacer la vue agrandie ou choisir un argument de vente', overviewNote: 'Vue d’ensemble du produit', trainingHubAria: 'Menu de formation produit', storyListAria: 'Fonctions du produit', interactiveViewAria: 'Vue interactive du produit', focusProgressAria: 'Progression de la mise au point', featureDetailAria: 'Détails de l’argument de vente', galleryBoardAria: 'Photothèque HD', galleryKicker: 'MOONDROP · PHOTOGRAPHIES ORIGINALES', galleryTitle: 'Photothèque HD', galleryIntro: 'Sélectionner une photo originale du produit ou de l’emballage.', galleryHeading: 'Photothèque produit HD', galleryDescription: 'Détails produit, port et emballage pour vos démonstrations.', reviewIntroTitle: 'Tests vérifiés, accès direct', inBox: 'DANS LA BOÎTE', warranty: 'GARANTIE', supportKicker: 'EMBALLAGE & GARANTIE', coreTag: 'VENTE', positioningTag: 'POSITION', supportTag: 'SERVICE', reviewsTag: 'TESTS', galleryTag: 'RESSOURCES' },
    it: { railTitle: '<span>Scopri il prodotto.</span><br><span>Impara a venderlo.</span>', viewerSubtitle: 'Vista principale · Dettagli del prodotto', stageSub: 'VISTA PRODOTTO · GUIDA ALLE FUNZIONI', stageAria: 'Scegli un dettaglio o un punto vendita', dragStageAria: 'Trascina la vista ingrandita o scegli un punto vendita', overviewNote: 'Panoramica del prodotto', trainingHubAria: 'Menu formazione prodotto', storyListAria: 'Funzioni del prodotto', interactiveViewAria: 'Vista interattiva del prodotto', focusProgressAria: 'Progresso della messa a fuoco', featureDetailAria: 'Dettagli del punto vendita', galleryBoardAria: 'Galleria immagini HD', galleryKicker: 'MOONDROP · FOTOGRAFIE ORIGINALI', galleryTitle: 'Galleria immagini HD', galleryIntro: 'Seleziona una foto originale del prodotto o della confezione.', galleryHeading: 'Galleria prodotto HD', galleryDescription: 'Dettagli del prodotto, uso e confezione per le dimostrazioni.', reviewIntroTitle: 'Test verificati, accesso diretto', inBox: 'CONTENUTO', warranty: 'GARANZIA', supportKicker: 'CONFEZIONE E GARANZIA', coreTag: 'VENDITA', positioningTag: 'POSIZIONE', supportTag: 'SERVIZIO', reviewsTag: 'TEST', galleryTag: 'RISORSE' },
    ru: { railTitle: '<span>Изучите продукт.</span><br><span>Освойте аргументы.</span>', viewerSubtitle: 'Главный вид · детали продукта', stageSub: 'ВИД ПРОДУКТА · ГИД ПО ФУНКЦИЯМ', stageAria: 'Выберите деталь или торговый аргумент', dragStageAria: 'Перемещайте увеличенный вид или выберите торговый аргумент', overviewNote: 'Обзор продукта', trainingHubAria: 'Меню обучения продукта', storyListAria: 'Особенности продукта', interactiveViewAria: 'Интерактивный вид продукта', focusProgressAria: 'Прогресс фокусировки', featureDetailAria: 'Детали торгового аргумента', galleryBoardAria: 'HD-галерея', galleryKicker: 'MOONDROP · ОРИГИНАЛЬНЫЕ ФОТО', galleryTitle: 'HD-галерея', galleryIntro: 'Выберите оригинальную фотографию продукта или упаковки.', galleryHeading: 'HD-галерея продукта', galleryDescription: 'Детали продукта, посадки и упаковки для демонстрации.', reviewIntroTitle: 'Проверенные обзоры, прямой доступ', inBox: 'В КОРОБКЕ', warranty: 'ГАРАНТИЯ', supportKicker: 'КОМПЛЕКТАЦИЯ И ГАРАНТИЯ', coreTag: 'ПРОДАЖА', positioningTag: 'ПОЗИЦИЯ', supportTag: 'СЕРВИС', reviewsTag: 'ОБЗОРЫ', galleryTag: 'МАТЕРИАЛЫ' }
  };
  Object.entries(compactExtras).forEach(([code, values]) => Object.assign(compact[code], values));

  window.MoondropLanguage = { languages, normalize, mobile, ui: (value) => { const code = normalize(value); return { product: product[code] || product.en, portal: portal[code] || portal.en, compact: code === 'zh' ? { language: '选择语言' } : (compact[code] || compact.en) }; } };

  function enhance(select) {
    if (!(select instanceof HTMLSelectElement)) return;
    const queryLanguage = normalize(new URLSearchParams(window.location.search).get('lang'));
    select.value = queryLanguage;
    select.addEventListener('change', (event) => {
      const url = new URL(window.location.href);
      url.searchParams.set('lang', normalize(event.target.value));
      window.location.assign(url.href);
    });
  }

  function run() {
    document.querySelectorAll('select.language-toggle').forEach(enhance);
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', run, { once: true });
  else run();
})();
