/* Product copy only. Story fields: chapter, label, title, body, points, show, say, spec, image caption. */
window.CHU3_COPY = {
  en: {
    intro: 'A compact wired starting point for music, everyday listening and games.',
    storyEyebrow: 'FIVE CORE SALES STORIES',
    masterAlt: 'CHU III earphones and detachable cable on a black background',
    heroAlt: 'Silver CHU III earphones beside bamboo leaves',
    colorsAlt: 'CHU III in silver and black',
    packageAlt: 'CHU III retail box, earphones, cable, ear tips, pouch and printed documents',
    galleryIntro: '14 original photographs, grouped by product, wearing and packaging. Open any image at its original resolution.',
    groups: ['Product', 'Wearing', 'Packaging'], original: 'Original photograph',
    galleryTitles: ['Black and silver housings', 'Silver pair with ear hooks', 'Black pair, front view', 'Black pair, angled view', 'Silver pair and complete cable', 'Black pair and complete cable', 'Black pair on a dark set', 'Silver pair on a dark set', 'Silver pair with bamboo', 'Silver pair in natural light', 'Wearing view, front', 'Wearing view, side', 'Complete package contents', 'Packaging, angled view'],
    prices: ['Regional suggested retail prices', 'Currency', 'Suggested retail price'],
    reviewNotes: ['A listening review of CHU III and its value proposition.', 'A look at the next generation of the CHU series.', 'CHU III compared with CHU II and other entry-level IEMs.'],
    stories: [
      ['Sound & tuning', '10 mm dynamic driver · Al-Mg dome', 'Start with a familiar song.', 'A 10 mm dynamic driver uses an aluminum-magnesium alloy composite diaphragm. CHU III combines this with acoustic tuning developed using the B&K 5128 measurement system. Let the customer judge voices, bass and detail with music they know.', [['Driver and housing differ', 'Al-Mg describes the diaphragm; the external housing is zinc alloy.'], ['Listen at a similar level', 'Ear-tip seal and volume affect the comparison. Avoid promising that a material alone guarantees better sound.']], 'Fit the tips, start at low volume and compare a familiar voice and bass passage at a similar listening level.', '“Let us try a song you know. Listen to the voice and bass, then tell me what you prefer.”', '10 mm dynamic driver · Al-Mg composite diaphragm · 16 Ω ±15% (@1 kHz)', 'Silver and black CHU III housings; the driver is inside, not exposed in this photograph.'],
      ['Build & fit', 'Zinc-alloy housing · around-ear fit', 'Small housings, a fit you can try.', 'Compact zinc-alloy housings come in black and silver. The cable runs around the ear, while S/M/L tips let you adjust the fit. A good seal supports bass and passive isolation; comfort varies from person to person.', [['Choose the tip first', 'Try the available sizes without forcing a deep insertion. A loose seal can reduce bass.'], ['Keep the distinction clear', 'Passive isolation is not active noise cancellation. Do not promise sweat resistance without a confirmed rating.']], 'Show both finishes. Match L/R, place the cable around the ear and let the customer try two tip sizes.', '“Try the fit first. The right tips should feel comfortable and keep the sound consistent.”', 'Zinc-alloy housing · black / silver · S/M/L ear tips', 'Around-ear wearing example; comfort and fit must be checked on the customer.'],
      ['Wired & easy to drive', '3.5 mm audio · no earphone charging', 'Check the socket, then press play.', 'The standard cable has a 3.5 mm stereo plug. Connect it to a headphone output; phones without that socket need a compatible audio adapter. The earphones do not need charging, and the connection avoids a Bluetooth transmission stage.', [['Match the source', 'A USB-C or Lightning adapter must support audio output on the actual device. An analog earphone does not need Bluetooth pairing.'], ['Explain gaming accurately', 'App, game, adapter and device processing can still add delay. Do not promise zero total latency or better game results.']], 'Check the customer’s device and output, lower the volume, connect the plug or adapter and test both music and video.', '“These do not need charging. Let us check your phone’s audio connection before you choose.”', '3.5 mm stereo · 16 Ω ±15% · 118 dB/Vrms (@1 kHz)', 'Complete silver pair and standard cable with 3.5 mm plug.'],
      ['Cable options', 'Detachable 0.78 mm 2-pin connection', 'Keep the earphones when your cable needs change.', 'The 0.78 mm 2-pin connection lets you replace a compatible cable. A microphone cable, balanced cable or wireless adapter is an optional accessory, not a built-in CHU III feature. Check both connector fit and source compatibility.', [['Connect carefully', 'Match L/R, pin orientation and polarity using the earphone and cable instructions. Hold the connector body and align the pins; do not pull the wire or force a misaligned plug.'], ['Choose the whole connection', 'A balanced cable requires a compatible balanced headphone output. A microphone requires a suitable cable and input path.']], 'Point out the 2-pin connectors and L/R marks. Explain the customer’s intended cable and output before disconnecting anything.', '“If you later need a microphone or a replacement cable, we can check a compatible option for these earphones.”', '0.78 mm 2-pin · detachable cable · optional accessories sold separately', 'Silver earphones with the cable connectors and around-ear sections visible.'],
      ['Care & maintenance', 'Ear tips · nozzle · cable storage', 'A few simple habits help keep them ready.', 'Keep ear tips and the nozzle opening clean and dry. Remove the tips for inspection, avoid pushing debris or liquid into the nozzle, and store the cable loosely in the pouch. Confirm the service method before attempting to remove a filter.', [['Keep cleaning gentle', 'Use a soft dry tool around the opening. Do not pierce the mesh or dismantle the housing.'], ['Find the cause first', 'For uneven or weak sound, check tip seal, visible blockage, cable seating and another source before arranging service.']], 'Show tip removal without touching the mesh, inspect the opening and demonstrate loose cable storage in the pouch.', '“If one side sounds quieter, check fit and visible blockage first. If it remains, we will help you follow the service process.”', 'Dry cleaning · no liquid in the nozzle · compatible cable replacement', 'Earphones, tips and storage pouch from the supplied package photograph.']
    ],
    comparisons: [
      ['Who it suits', '“I want my first wired pair.”', 'A compact choice for music, desk use and games when you have a suitable headphone output. Try fit and cable routing; an adapter may be needed for your phone.', '3.5 mm connection · detachable cable'],
      ['Compared with Bluetooth', '“Why choose a cable?”', 'CHU III needs no earphone charging or pairing and avoids Bluetooth transmission. Bluetooth offers more freedom of movement and may include ANC or calls; choose around your routine.', 'Cable convenience versus wireless freedom'],
      ['Compared with open-ear designs', '“I need to hear the room.”', 'CHU III seals the canal with tips for passive isolation. Open-ear designs leave it unsealed and may suit ongoing awareness. Compare the actual fit and environment.', 'Different wearing and isolation needs'],
      ['Compared with over-ear headphones', '“I want something easy to carry.”', 'CHU III takes little bag space but uses tips in the ear canal. Over-ear headphones avoid that tip fit but are larger. Let comfort decide instead of assuming one format always sounds better.', 'Compact storage versus wearing preference']
    ],
    support: {
      contents: ['CHU III earphones', 'Standard 3.5 mm cable', 'Storage pouch', 'S/M/L ear tips', 'Wearing guide card', 'User manual', 'Certificate of conformity'],
      packageNote: 'Original photograph of the supplied standard package. Optional cables and phone adapters are not included.',
      periods: [['CHU III earphones', '1 year'], ['Included accessories', '90 days']],
      policy: 'Coverage for performance faults not caused by misuse follows the purchase region and local sales-channel terms. Warranty service does not mean automatic replacement.',
      exclusions: ['Check the purchase date, receipt and fault symptoms.', 'Check the source, tip seal and cable connection before arranging service.', 'Follow the local service process; damage from misuse, liquid or unauthorized repair is outside the supplied warranty terms.']
    }
  },
  zh: {
    intro: '从一副小巧的有线耳机开始，体验音乐、日常聆听与游戏。',
    storyEyebrow: '五个核心销售卖点',
    masterAlt: '黑色背景上的竹3耳机与可拆卸线材', heroAlt: '竹叶旁的银色竹3耳机', colorsAlt: '竹3银色与黑色两款外观',
    packageAlt: '竹3包装盒、耳机、线材、耳塞套、收纳袋与随附资料',
    galleryIntro: '14张原始照片，按产品外观、佩戴和包装分组。点击任意图片查看原始分辨率。',
    groups: ['产品外观', '佩戴', '包装'], original: '原始实拍',
    galleryTitles: ['黑银双色腔体', '银色双耳与耳挂线', '黑色双耳正面', '黑色双耳侧面', '银色双耳与完整线材', '黑色双耳与完整线材', '黑色双耳暗背景实拍', '银色双耳暗背景实拍', '竹叶中的银色双耳', '自然光下的银色双耳', '正面佩戴示意', '侧面佩戴示意', '完整包装内容', '包装与配件斜角实拍'],
    prices: ['各地区建议零售价', '币种', '建议零售价'],
    reviewNotes: ['竹3的试听体验与产品价值介绍。', '围绕竹系列新一代产品的评测。', '竹3与竹2及其他入门入耳式耳机的对比。'],
    stories: [
      ['声音与调音', '10mm动圈 · 铝镁合金球顶', '先用一首熟悉的歌来听。', '10mm动圈采用铝镁合金复合振膜，并结合基于B&K 5128测量系统的声学调音。让顾客用熟悉的音乐判断人声、低频和细节，而不是只看材料名称。', [['分清振膜与外壳', '铝镁合金用于振膜，外部腔体为锌合金，两者不能混淆。'], ['在相近音量下比较', '耳塞密封和播放音量都会影响听感，不把单一材料等同于音质保证。']], '先选好耳塞套，从低音量开始，用熟悉的人声和低频片段在相近音量下试听。', '“我们先听你熟悉的歌，留意人声和低频，再说说你更喜欢哪种表现。”', '10mm动圈 · 铝镁合金复合振膜 · 16Ω±15%（@1kHz）', '竹3银色与黑色腔体实拍；单元位于内部，照片未展示内部结构。'],
      ['做工与佩戴', '锌合金腔体 · 绕耳佩戴', '小巧的腔体，先试适合自己的贴合。', '紧凑的锌合金腔体提供黑色和银色两种外观。线材绕耳佩戴，S/M/L三种耳塞套用于调整贴合。良好密封有助于低频与被动隔音，舒适度仍需本人试戴。', [['先选耳塞套', '试戴合适尺寸，不强行深塞；密封不足可能让低频变少。'], ['说明隔音边界', '被动隔音不是主动降噪，未确认防护等级时不承诺防汗或运动防水。']], '展示两种颜色，核对左右标识，将线材绕耳，并让顾客比较两种耳塞尺寸。', '“先试佩戴。合适的耳塞套应当舒服，声音也更稳定。”', '锌合金腔体 · 黑色／银色 · S/M/L耳塞套', '绕耳佩戴示意；实际舒适度和贴合程度以本人试戴为准。'],
      ['有线连接与易驱动', '3.5mm音频 · 耳机无需充电', '确认接口，接好就能听。', '标准线材配备3.5mm立体声插头，接入耳机输出即可使用；没有该接口的手机需要兼容的音频转接器。耳机本身无需充电，也省去了蓝牙传输环节。', [['匹配音源设备', 'USB-C或Lightning转接器需支持当前设备的音频输出；模拟耳机无需蓝牙配对。'], ['准确解释游戏体验', '游戏、软件、转接器和设备处理仍可能产生延迟，不承诺整条链路零延迟或提升游戏成绩。']], '确认顾客设备和输出接口，调低音量后接好插头或转接器，分别测试音乐与视频。', '“这副耳机不用充电。先看看你的手机怎么接音频，再决定是否需要转接器。”', '3.5mm立体声 · 16Ω±15% · 118dB/Vrms（@1kHz）', '银色双耳及带3.5mm插头的标准线材全貌。'],
      ['换线与使用扩展', '0.78mm双针可换线', '需求变了，可以先换合适的线。', '0.78mm双针接口支持更换兼容线材。麦克风线、平衡线或蓝牙适配器属于选配附件，不是竹3内置功能；需要同时确认插针结构和音源兼容性。', [['正确插拔', '按耳机与线材说明核对左右声道、插针方向及极性，握住接头本体并对齐，不拉扯导线、不强插错位插针。'], ['确认完整连接', '平衡线需连接兼容的平衡耳机输出；通话则需要合适的麦克风线和输入链路。']], '指出双针接口与左右标识，先确认顾客想用的线材和音源，再示范连接方式。', '“以后需要麦克风或更换线材时，可以先为这副耳机选一条兼容的线。”', '0.78mm双针 · 可拆卸线材 · 扩展附件另购', '银色耳机的线材接头与绕耳部分实拍。'],
      ['维护与长期使用', '耳塞套 · 导管 · 线材收纳', '做好日常维护，使用更省心。', '让耳塞套和导管开口保持干净、干燥。取下耳塞套检查时，不将污物或液体推入导管；线材松弛收好后放入收纳袋。拆卸滤网前先确认适用的售后维护方式。', [['温和清洁', '使用柔软、干燥的工具清理开口周围，不刺穿滤网，也不自行拆开腔体。'], ['先排查原因', '音量变小或左右不一致时，先查贴合、可见堵塞、线材连接，再换音源对比。']], '展示取下耳塞套并检查开口的方法，不接触滤网；再示范松弛盘线放入收纳袋。', '“如果一边变小声，先看看贴合和可见堵塞；仍有问题，我们再协助走售后流程。”', '干燥清洁 · 避免液体进入导管 · 可更换兼容线材', '包装实拍中的耳机、耳塞套和收纳袋。']
    ],
    comparisons: [
      ['适合什么人', '“我想买第一副有线耳机。”', '适合有兼容耳机输出、希望用于听歌、桌面或游戏的人。先体验佩戴和线材走向；部分手机需要另配音频转接器。', '3.5mm连接 · 可换线'],
      ['对比蓝牙耳机', '“为什么选有线？”', '竹3不用给耳机充电或配对，也省去蓝牙传输环节；蓝牙耳机活动更自由，部分产品带主动降噪和通话功能。按日常使用方式选择。', '有线使用习惯与无线活动自由度的取舍'],
      ['对比开放式耳机', '“我需要听见周围。”', '竹3用耳塞套密封耳道，提供被动隔音；开放式设计不封闭耳道，适合持续感知环境。结合实际环境和佩戴偏好比较。', '佩戴形式与隔音需求不同'],
      ['对比头戴式耳机', '“我想要方便随身带的。”', '竹3占用收纳空间较小，但需要适应入耳耳塞；头戴式不需要耳塞套进入耳道，却更占空间。让实际舒适度决定，不笼统断言哪种形式音质更好。', '便携收纳与佩戴偏好的取舍']
    ],
    support: {
      contents: ['竹3耳机', '标准3.5mm耳机线', '收纳袋', 'S/M/L耳塞套', '佩戴指引卡', '使用说明书', '合格证'],
      packageNote: '标准包装原始实拍；选配线材和手机音频转接器不在清单内。',
      periods: [['竹3耳机本体', '1年'], ['随附配件', '90天']],
      policy: '非人为性能故障的保修服务按购买地区及当地渠道条款执行；保修服务不等于自动换新。',
      exclusions: ['核对购买日期、购买凭证与故障现象。', '先排查音源、耳塞贴合与线材连接，再安排售后。', '遵循当地售后流程；误用、进液或未经授权维修造成的损坏不在课件所列保修范围内。']
    }
  }
};
Object.assign(window.CHU3_COPY, {
 de: {
  intro:'Ein kompakter Einstieg mit Kabel für Musik, den Alltag und Spiele.', storyEyebrow:'FÜNF ZENTRALE VERKAUFSARGUMENTE',
  masterAlt:'CHU III mit abnehmbarem Kabel vor schwarzem Hintergrund',heroAlt:'Silberne CHU III neben Bambusblättern',colorsAlt:'CHU III in Silber und Schwarz',packageAlt:'CHU III mit Verpackung, Kabel, Ohrpassstücken, Beutel und Unterlagen',
  galleryIntro:'14 Originalfotos, geordnet nach Produkt, Trageansicht und Verpackung. Jedes Bild lässt sich in Originalauflösung öffnen.',groups:['Produkt','Trageansicht','Verpackung'],original:'Originalfoto',
  galleryTitles:['Schwarze und silberne Gehäuse','Silbernes Paar mit Ohrbügeln','Schwarzes Paar von vorn','Schwarzes Paar schräg','Silbernes Paar mit vollständigem Kabel','Schwarzes Paar mit vollständigem Kabel','Schwarzes Paar vor dunklem Hintergrund','Silbernes Paar vor dunklem Hintergrund','Silbernes Paar mit Bambus','Silbernes Paar bei Tageslicht','Trageansicht von vorn','Trageansicht von der Seite','Vollständiger Lieferumfang','Verpackung und Zubehör schräg'],
  prices:['Unverbindliche Preisempfehlungen nach Region','Währung','Unverbindliche Preisempfehlung'],reviewNotes:['Höreindrücke zum CHU III und seinem Preis-Leistungs-Verhältnis.','Ein Blick auf die nächste Generation der CHU-Serie.','CHU III im Vergleich mit CHU II und weiteren Einsteiger-In-Ears.'],
  stories:[
   ['Klang & Abstimmung','10-mm-Dynamiktreiber · Al-Mg-Kalotte','Mit einem vertrauten Lied beginnen.','Der 10-mm-Dynamiktreiber besitzt eine Verbundmembran aus Aluminium-Magnesium-Legierung. Die akustische Abstimmung wurde mit dem Messsystem B&K 5128 entwickelt. Stimmen, Bass und Details sollten mit vertrauter Musik beurteilt werden.',[['Membran und Gehäuse unterscheiden','Al-Mg bezeichnet die Membran; das Außengehäuse besteht aus Zinklegierung.'],['Bei ähnlicher Lautstärke vergleichen','Abdichtung und Lautstärke beeinflussen den Eindruck. Ein Material allein garantiert keinen besseren Klang.']],'Passstücke anpassen, leise beginnen und eine vertraute Gesangs- und Basspassage bei ähnlicher Lautstärke vergleichen.','„Hören wir ein Lied, das Sie kennen. Achten Sie auf Stimme und Bass und sagen Sie, was Ihnen gefällt.“','10-mm-Dynamiktreiber · Al-Mg-Verbundmembran · 16 Ω ±15 % (@1 kHz)','Silberne und schwarze Gehäuse; der innenliegende Treiber ist auf diesem Foto nicht sichtbar.'],
   ['Verarbeitung & Sitz','Zinklegierung · Kabelführung über dem Ohr','Kleine Gehäuse, selbst ausprobierter Sitz.','Die kompakten Gehäuse aus Zinklegierung gibt es in Schwarz und Silber. Das Kabel verläuft über dem Ohr; Passstücke in S/M/L helfen beim Anpassen. Eine gute Abdichtung unterstützt Bass und passive Isolation. Der Komfort ist individuell.',[['Passstücke zuerst wählen','Verschiedene Größen ohne tiefes Hineindrücken probieren. Eine lockere Abdichtung kann den Bass schwächen.'],['Isolation richtig erklären','Passive Isolation ist keine aktive Geräuschunterdrückung. Ohne bestätigte Schutzklasse keine Schweißfestigkeit zusagen.']],'Beide Farben zeigen, L/R zuordnen, das Kabel über das Ohr legen und zwei Passstückgrößen ausprobieren lassen.','„Probieren Sie zuerst den Sitz. Passende Aufsätze sollten bequem sein und einen gleichmäßigen Klang ermöglichen.“','Zinklegierung · Schwarz / Silber · Passstücke S/M/L','Beispiel der Kabelführung über dem Ohr; Sitz und Komfort individuell prüfen.'],
   ['Kabel & Antrieb','3,5-mm-Audio · kein Laden der Ohrhörer','Anschluss prüfen, dann hören.','Das Standardkabel hat einen 3,5-mm-Stereostecker für einen Kopfhörerausgang. Telefone ohne diese Buchse benötigen einen kompatiblen Audioadapter. Die Ohrhörer brauchen keine Ladung und umgehen die Bluetooth-Übertragung.',[['Quelle passend wählen','Ein USB-C- oder Lightning-Adapter muss die Audioausgabe am konkreten Gerät unterstützen. Analoge Ohrhörer benötigen keine Bluetooth-Kopplung.'],['Spiele sachlich erklären','App, Spiel, Adapter und Gerät können weiterhin Verzögerungen verursachen. Keine Gesamtlatenz von null oder besseren Spielergebnisse versprechen.']],'Gerät und Ausgang prüfen, Lautstärke senken, Stecker oder Adapter verbinden und Musik sowie Video testen.','„Diese Ohrhörer müssen nicht geladen werden. Prüfen wir zuerst den Audioanschluss Ihres Telefons.“','3,5-mm-Stereo · 16 Ω ±15 % · 118 dB/Vrms (@1 kHz)','Silbernes Paar mit vollständigem Standardkabel und 3,5-mm-Stecker.'],
   ['Kabeloptionen','Abnehmbarer 0,78-mm-2-Pin-Anschluss','Das Kabel dem Bedarf anpassen.','Der 0,78-mm-2-Pin-Anschluss erlaubt ein kompatibles Ersatzkabel. Mikrofonkabel, symmetrische Kabel und Funkadapter sind optionales Zubehör, keine eingebauten Funktionen. Passform des Anschlusses und Kompatibilität der Quelle prüfen.',[['Sorgfältig verbinden','L/R, Stiftausrichtung und Polarität anhand der Anleitungen für Ohrhörer und Kabel prüfen. Am Steckergehäuse halten, Stifte ausrichten und weder am Draht ziehen noch Gewalt anwenden.'],['Die gesamte Verbindung prüfen','Ein symmetrisches Kabel benötigt einen passenden symmetrischen Kopfhörerausgang. Ein Mikrofon braucht ein geeignetes Kabel und einen passenden Eingangsweg.']],'2-Pin-Anschlüsse und L/R-Markierungen zeigen. Vor dem Abziehen geplantes Kabel und Ausgang erklären.','„Wenn Sie später ein Mikrofon oder ein Ersatzkabel brauchen, prüfen wir eine kompatible Lösung.“','0,78-mm-2-Pin · abnehmbares Kabel · optionales Zubehör separat','Silberne Ohrhörer mit sichtbaren Kabelanschlüssen und Ohrbügelabschnitten.'],
   ['Pflege & Nutzung','Passstücke · Schallöffnung · Kabel','Einfache Pflege für den Alltag.','Passstücke und Schallöffnung sauber und trocken halten. Zum Prüfen die Aufsätze abnehmen, keinen Schmutz oder Flüssigkeit hineindrücken und das Kabel locker im Beutel verstauen. Vor einer Filterentfernung die geeignete Servicemethode klären.',[['Schonend reinigen','Ein weiches, trockenes Hilfsmittel um die Öffnung verwenden. Das Gitter nicht durchstechen und das Gehäuse nicht zerlegen.'],['Zuerst die Ursache prüfen','Bei schwachem oder ungleichem Klang Abdichtung, sichtbare Verstopfung, Kabelsitz und eine andere Quelle prüfen.']],'Aufsatz abnehmen, ohne das Gitter zu berühren, Öffnung prüfen und lockeres Verstauen des Kabels zeigen.','„Ist eine Seite leiser, prüfen Sie zunächst Sitz und sichtbare Verstopfung. Bleibt das Problem, helfen wir beim Service.“','Trocken reinigen · keine Flüssigkeit in die Öffnung · kompatibles Ersatzkabel','Ohrhörer, Passstücke und Beutel auf dem Originalfoto des Lieferumfangs.']
  ],
  comparisons:[['Für wen geeignet?','„Ich suche meine ersten kabelgebundenen Ohrhörer.“','Eine kompakte Wahl für Musik, Schreibtisch und Spiele mit geeignetem Kopfhörerausgang. Sitz und Kabelführung testen; am Telefon kann ein Adapter nötig sein.','3,5-mm-Anschluss · abnehmbares Kabel'],['Gegenüber Bluetooth','„Warum ein Kabel?“','CHU III benötigt weder Ladung noch Kopplung und umgeht Bluetooth. Bluetooth bietet mehr Bewegungsfreiheit und je nach Modell ANC oder Telefonie. Entscheidend ist der Alltag.','Kabelnutzung und kabellose Bewegungsfreiheit abwägen'],['Gegenüber offenen Ohrhörern','„Ich möchte meine Umgebung hören.“','CHU III dichtet den Gehörgang für passive Isolation ab. Offene Bauformen lassen ihn offen und können für ständige Umgebungswahrnehmung passen. Sitz und Einsatzort vergleichen.','Unterschiedliche Trage- und Isolationsbedürfnisse'],['Gegenüber Over-Ear-Kopfhörern','„Ich möchte etwas leicht Transportierbares.“','CHU III benötigt wenig Platz, sitzt aber mit Passstücken im Gehörgang. Over-Ears vermeiden diesen Sitz, sind jedoch größer. Nach Komfort entscheiden, ohne einer Bauform pauschal besseren Klang zuzuschreiben.','Kompaktes Verstauen und Tragevorlieben abwägen']],
  support:{contents:['CHU III Ohrhörer','Standardkabel mit 3,5-mm-Stecker','Aufbewahrungsbeutel','Passstücke S/M/L','Trageanleitungskarte','Bedienungsanleitung','Konformitätsbescheinigung'],packageNote:'Originalfoto des Standardlieferumfangs. Optionale Kabel und Telefonadapter sind nicht enthalten.',periods:[['CHU III Ohrhörer','1 Jahr'],['Mitgeliefertes Zubehör','90 Tage']],policy:'Die Abdeckung nicht durch Fehlgebrauch verursachter Funktionsfehler richtet sich nach Kaufregion und örtlichen Händlerbedingungen. Garantieservice bedeutet keinen automatischen Austausch.',exclusions:['Kaufdatum, Beleg und Fehlerbild prüfen.','Quelle, Abdichtung und Kabelanschluss vor dem Service prüfen.','Den örtlichen Serviceablauf befolgen. Schäden durch Fehlgebrauch, Flüssigkeit oder unbefugte Reparatur sind nach den vorliegenden Bedingungen ausgeschlossen.']}
 },
 es:{
  intro:'Una opción compacta con cable para música, escucha diaria y juegos.',storyEyebrow:'CINCO ARGUMENTOS CLAVE DE VENTA',masterAlt:'CHU III y cable desmontable sobre fondo negro',heroAlt:'CHU III plateados junto a hojas de bambú',colorsAlt:'CHU III en plata y negro',packageAlt:'Caja, auriculares CHU III, cable, almohadillas, bolsa y documentos',galleryIntro:'14 fotografías originales, agrupadas por producto, uso y embalaje. Abre cualquier imagen a su resolución original.',groups:['Producto','Uso','Embalaje'],original:'Fotografía original',galleryTitles:['Carcasas negras y plateadas','Par plateado con guías sobre la oreja','Par negro de frente','Par negro en ángulo','Par plateado con cable completo','Par negro con cable completo','Par negro sobre fondo oscuro','Par plateado sobre fondo oscuro','Par plateado con bambú','Par plateado con luz natural','Uso visto de frente','Uso visto de lado','Contenido completo del paquete','Embalaje y accesorios en ángulo'],prices:['Precios de venta recomendados por región','Moneda','Precio de venta recomendado'],reviewNotes:['Impresiones de escucha y relación calidad-precio del CHU III.','Una mirada a la nueva generación de la serie CHU.','Comparación del CHU III con CHU II y otros IEM de entrada.'],
  stories:[
   ['Sonido y ajuste acústico','Transductor dinámico de 10 mm · cúpula Al-Mg','Empieza con una canción conocida.','El transductor dinámico de 10 mm utiliza un diafragma compuesto de aleación de aluminio y magnesio. Su ajuste acústico se desarrolló con el sistema de medición B&K 5128. Deja que el cliente valore voces, graves y detalles con música conocida.',[['Distingue diafragma y carcasa','Al-Mg describe el diafragma; la carcasa exterior es de aleación de zinc.'],['Compara a un volumen similar','El sellado y el volumen influyen. Un material por sí solo no garantiza mejor sonido.']],'Ajusta las almohadillas, empieza a bajo volumen y compara voces y graves conocidos a un nivel similar.','«Probemos una canción que conozcas. Escucha la voz y los graves y dime qué prefieres».','Transductor dinámico de 10 mm · diafragma compuesto Al-Mg · 16 Ω ±15 % (@1 kHz)','Carcasas plateadas y negras; el transductor está dentro y no aparece expuesto.'],
   ['Construcción y ajuste','Carcasa de zinc · cable sobre la oreja','Carcasas pequeñas: prueba cómo se adaptan.','Las carcasas compactas de aleación de zinc se ofrecen en negro y plata. El cable pasa sobre la oreja y las almohadillas S/M/L permiten ajustar el sellado. Un buen sellado favorece los graves y el aislamiento pasivo; la comodidad es personal.',[['Elige primero la almohadilla','Prueba tamaños sin forzar una inserción profunda. Un sellado flojo puede reducir los graves.'],['Explica el aislamiento','El aislamiento pasivo no es cancelación activa. Sin una clasificación confirmada, no prometas resistencia al sudor.']],'Muestra ambos acabados, comprueba L/R, coloca el cable sobre la oreja y permite probar dos tamaños.','«Prueba primero el ajuste. Las almohadillas adecuadas deben resultar cómodas y mantener un sonido uniforme».','Aleación de zinc · negro / plata · almohadillas S/M/L','Ejemplo de uso sobre la oreja; comprobar comodidad y ajuste con cada persona.'],
   ['Conexión y facilidad de uso','Audio de 3,5 mm · sin cargar los auriculares','Comprueba la toma y reproduce.','El cable estándar tiene un conector estéreo de 3,5 mm para una salida de auriculares. Los teléfonos sin esta toma necesitan un adaptador de audio compatible. Los auriculares no necesitan carga y evitan la etapa de transmisión Bluetooth.',[['Comprueba la fuente','El adaptador USB-C o Lightning debe admitir la salida de audio del dispositivo concreto. Un auricular analógico no necesita emparejamiento Bluetooth.'],['Describe bien los juegos','La aplicación, el juego, el adaptador y el dispositivo pueden añadir retardo. No prometas latencia total cero ni mejores resultados.']],'Comprueba dispositivo y salida, baja el volumen, conecta el cable o adaptador y prueba música y vídeo.','«No necesitan carga. Revisemos la conexión de audio de tu teléfono antes de elegir».','Estéreo de 3,5 mm · 16 Ω ±15 % · 118 dB/Vrms (@1 kHz)','Par plateado completo con cable estándar y conector de 3,5 mm.'],
   ['Opciones de cable','Conexión desmontable de 2 pines de 0,78 mm','Adapta el cable a tus necesidades.','La conexión de 2 pines de 0,78 mm permite sustituir el cable por uno compatible. El cable con micrófono, el balanceado y el adaptador inalámbrico son accesorios opcionales, no funciones integradas. Comprueba conector y fuente.',[['Conecta con cuidado','Comprueba L/R, orientación y polaridad de los pines según las instrucciones del auricular y el cable. Sujeta el cuerpo del conector, alinea los pines y no tires del hilo ni fuerces la conexión.'],['Comprueba toda la conexión','Un cable balanceado necesita una salida balanceada compatible. El micrófono requiere cable y ruta de entrada adecuados.']],'Señala conectores y marcas L/R. Explica el cable y la salida previstos antes de desconectar.','«Si después necesitas un micrófono o un cable de repuesto, podemos revisar una opción compatible».','2 pines de 0,78 mm · cable desmontable · accesorios opcionales aparte','Auriculares plateados con conectores y tramos sobre la oreja visibles.'],
   ['Cuidado y mantenimiento','Almohadillas · boquilla · cable','Unos hábitos sencillos para el día a día.','Mantén almohadillas y abertura de la boquilla limpias y secas. Retira las almohadillas para revisar, evita empujar suciedad o líquido al interior y guarda el cable holgado en la bolsa. Confirma el procedimiento de servicio antes de retirar un filtro.',[['Limpia suavemente','Usa una herramienta suave y seca alrededor de la abertura. No perfores la malla ni desmontes la carcasa.'],['Busca primero la causa','Si el sonido es débil o desigual, revisa sellado, obstrucciones visibles, cable y otra fuente antes del servicio.']],'Muestra cómo retirar la almohadilla sin tocar la malla, inspeccionar la abertura y guardar el cable sin apretarlo.','«Si un lado suena más bajo, revisa ajuste y obstrucciones visibles. Si persiste, te ayudaremos con el servicio».','Limpieza en seco · sin líquido en la boquilla · cable compatible reemplazable','Auriculares, almohadillas y bolsa en la fotografía original del paquete.']
  ],comparisons:[['Para quién es','«Quiero mis primeros auriculares con cable».','Una opción compacta para música, escritorio y juegos con una salida adecuada. Prueba ajuste y recorrido del cable; tu teléfono puede necesitar adaptador.','Conexión de 3,5 mm · cable desmontable'],['Frente a Bluetooth','«¿Por qué elegir cable?»','CHU III no necesita carga ni emparejamiento y evita la transmisión Bluetooth. Bluetooth da más libertad de movimiento y puede incluir ANC o llamadas. Elige según tu rutina.','Uso con cable frente a libertad inalámbrica'],['Frente a diseños abiertos','«Necesito oír el entorno».','CHU III sella el canal con almohadillas para aislar pasivamente. Los diseños abiertos lo dejan libre y pueden servir para mantener la percepción del entorno. Compara ajuste y ambiente reales.','Distintas necesidades de uso y aislamiento'],['Frente a auriculares de diadema','«Quiero algo fácil de llevar».','CHU III ocupa poco espacio, pero usa almohadillas dentro del canal. Los de diadema evitan ese ajuste, aunque son más grandes. Decide por comodidad sin asumir que un formato siempre suena mejor.','Tamaño de transporte y preferencias de uso']],
  support:{contents:['Auriculares CHU III','Cable estándar de 3,5 mm','Bolsa de transporte','Almohadillas S/M/L','Tarjeta de colocación','Manual de usuario','Certificado de conformidad'],packageNote:'Fotografía original del paquete estándar. No incluye cables opcionales ni adaptadores para teléfono.',periods:[['Auriculares CHU III','1 año'],['Accesorios incluidos','90 días']],policy:'La cobertura de fallos de funcionamiento no causados por mal uso depende de la región de compra y las condiciones del canal local. La garantía no implica sustitución automática.',exclusions:['Comprueba fecha de compra, justificante y síntomas.','Revisa fuente, sellado y conexión del cable antes del servicio.','Sigue el proceso local. Los daños por mal uso, líquidos o reparación no autorizada quedan fuera de las condiciones facilitadas.']}
 }
});
Object.assign(window.CHU3_COPY, {
 pt:{
  intro:'Uma opção compacta com fio para música, uso diário e jogos.',storyEyebrow:'CINCO ARGUMENTOS PRINCIPAIS DE VENDA',masterAlt:'CHU III e cabo removível sobre fundo preto',heroAlt:'CHU III prateados ao lado de folhas de bambu',colorsAlt:'CHU III nas cores prata e preto',packageAlt:'Caixa, fones CHU III, cabo, ponteiras, bolsa e documentos',galleryIntro:'14 fotografias originais, agrupadas por produto, uso e embalagem. Abra qualquer imagem na resolução original.',groups:['Produto','Uso','Embalagem'],original:'Fotografia original',galleryTitles:['Corpos pretos e prateados','Par prateado com guias sobre a orelha','Par preto de frente','Par preto em ângulo','Par prateado com cabo completo','Par preto com cabo completo','Par preto em cenário escuro','Par prateado em cenário escuro','Par prateado com bambu','Par prateado à luz natural','Uso visto de frente','Uso visto de lado','Conteúdo completo da embalagem','Embalagem e acessórios em ângulo'],prices:['Preços de venda sugeridos por região','Moeda','Preço de venda sugerido'],reviewNotes:['Impressões de escuta e relação custo-benefício do CHU III.','Um olhar sobre a nova geração da série CHU.','Comparação do CHU III com CHU II e outros IEMs de entrada.'],
  stories:[
   ['Som e ajuste acústico','Driver dinâmico de 10 mm · cúpula Al-Mg','Comece com uma música conhecida.','O driver dinâmico de 10 mm usa um diafragma composto de liga de alumínio e magnésio. O ajuste acústico foi desenvolvido com o sistema de medição B&K 5128. Deixe o cliente avaliar vozes, graves e detalhes com músicas conhecidas.',[['Diferencie diafragma e corpo','Al-Mg descreve o diafragma; o corpo externo é de liga de zinco.'],['Compare em volume semelhante','Vedação e volume influenciam a escuta. Um material isolado não garante som melhor.']],'Ajuste as ponteiras, comece em volume baixo e compare um trecho conhecido de voz e graves em volume semelhante.','“Vamos ouvir uma música que você conhece. Preste atenção na voz e nos graves e diga o que prefere.”','Driver dinâmico de 10 mm · diafragma composto Al-Mg · 16 Ω ±15% (@1 kHz)','Corpos prateados e pretos; o driver fica dentro e não está exposto na foto.'],
   ['Construção e encaixe','Corpo de zinco · cabo sobre a orelha','Corpos pequenos: experimente o encaixe.','Os corpos compactos de liga de zinco vêm em preto e prata. O cabo passa sobre a orelha e as ponteiras S/M/L ajudam no ajuste. Uma boa vedação favorece graves e isolamento passivo; o conforto varia entre pessoas.',[['Escolha primeiro a ponteira','Experimente tamanhos sem forçar a inserção profunda. Uma vedação frouxa pode reduzir os graves.'],['Explique o isolamento','Isolamento passivo não é cancelamento ativo. Sem classificação confirmada, não prometa resistência ao suor.']],'Mostre as duas cores, confira L/R, passe o cabo sobre a orelha e deixe o cliente testar dois tamanhos.','“Experimente o encaixe primeiro. As ponteiras certas devem ser confortáveis e manter o som consistente.”','Liga de zinco · preto / prata · ponteiras S/M/L','Exemplo de uso com cabo sobre a orelha; verifique conforto e encaixe individualmente.'],
   ['Conexão e facilidade de uso','Áudio de 3,5 mm · fones sem recarga','Confira a saída e dê o play.','O cabo padrão tem plugue estéreo de 3,5 mm para uma saída de fones. Celulares sem essa entrada precisam de adaptador de áudio compatível. Os fones não precisam de carga e dispensam a etapa de transmissão Bluetooth.',[['Combine com a fonte','O adaptador USB-C ou Lightning precisa suportar áudio no aparelho usado. Fones analógicos não exigem pareamento Bluetooth.'],['Explique os jogos com precisão','Aplicativo, jogo, adaptador e aparelho ainda podem acrescentar atraso. Não prometa latência total zero nem melhores resultados.']],'Confira aparelho e saída, reduza o volume, conecte o plugue ou adaptador e teste música e vídeo.','“Estes fones não precisam de carga. Vamos verificar a conexão de áudio do seu celular antes da escolha.”','Estéreo de 3,5 mm · 16 Ω ±15% · 118 dB/Vrms (@1 kHz)','Par prateado com cabo padrão completo e plugue de 3,5 mm.'],
   ['Opções de cabo','Conexão removível de 2 pinos de 0,78 mm','Adapte o cabo quando a necessidade mudar.','A conexão de 2 pinos de 0,78 mm permite usar um cabo de reposição compatível. Cabo com microfone, cabo balanceado e adaptador sem fio são acessórios opcionais, não funções integradas. Confira encaixe do conector e compatibilidade da fonte.',[['Conecte com cuidado','Confira L/R, orientação e polaridade dos pinos conforme as instruções dos fones e do cabo. Segure o corpo do conector, alinhe os pinos e não puxe o fio nem force o encaixe.'],['Confira a conexão completa','Um cabo balanceado exige saída balanceada compatível. O microfone precisa de cabo e caminho de entrada adequados.']],'Mostre os conectores e as marcas L/R. Explique o cabo e a saída desejados antes de desconectar.','“Se depois precisar de microfone ou cabo de reposição, podemos conferir uma opção compatível.”','2 pinos de 0,78 mm · cabo removível · acessórios opcionais separados','Fones prateados com conectores e trechos sobre a orelha visíveis.'],
   ['Cuidados e manutenção','Ponteiras · bocal · cabo','Hábitos simples para o uso diário.','Mantenha as ponteiras e a abertura do bocal limpas e secas. Retire as ponteiras para inspecionar, não empurre sujeira ou líquido para dentro e guarde o cabo sem apertar na bolsa. Confirme o procedimento de assistência antes de retirar um filtro.',[['Limpe com delicadeza','Use um utensílio macio e seco ao redor da abertura. Não perfure a tela nem desmonte o corpo.'],['Procure primeiro a causa','Se o som estiver fraco ou desigual, confira vedação, bloqueios visíveis, encaixe do cabo e outra fonte antes da assistência.']],'Demonstre como retirar a ponteira sem tocar na tela, inspecionar a abertura e guardar o cabo folgado.','“Se um lado ficar mais baixo, confira o encaixe e bloqueios visíveis. Se continuar, ajudaremos com a assistência.”','Limpeza a seco · sem líquido no bocal · cabo compatível substituível','Fones, ponteiras e bolsa na foto original do conteúdo da embalagem.']
  ],comparisons:[['Para quem serve','“Quero meu primeiro fone com fio.”','Uma opção compacta para música, mesa e jogos com saída de fones adequada. Teste encaixe e posição do cabo; o celular pode precisar de adaptador.','Conexão de 3,5 mm · cabo removível'],['Em relação ao Bluetooth','“Por que escolher um cabo?”','CHU III não exige carga nem pareamento e dispensa a transmissão Bluetooth. Bluetooth oferece mais liberdade de movimento e pode incluir ANC ou chamadas. Escolha conforme a rotina.','Uso com fio e liberdade sem fio'],['Em relação a modelos abertos','“Preciso ouvir o ambiente.”','CHU III veda o canal com ponteiras para isolamento passivo. Modelos abertos deixam o canal livre e podem atender à percepção contínua do ambiente. Compare encaixe e local de uso.','Necessidades diferentes de uso e isolamento'],['Em relação a headphones','“Quero algo fácil de levar.”','CHU III ocupa pouco espaço, mas usa ponteiras no canal. Headphones evitam esse encaixe, porém são maiores. Deixe o conforto decidir, sem presumir que um formato sempre soa melhor.','Transporte compacto e preferência de uso']],
  support:{contents:['Fones CHU III','Cabo padrão de 3,5 mm','Bolsa de armazenamento','Ponteiras S/M/L','Cartão com instruções de uso','Manual do usuário','Certificado de conformidade'],packageNote:'Fotografia original do pacote padrão. Cabos opcionais e adaptadores para celular não estão incluídos.',periods:[['Fones CHU III','1 ano'],['Acessórios incluídos','90 dias']],policy:'A cobertura de falhas de desempenho sem mau uso segue a região de compra e os termos do canal local. Atendimento em garantia não significa troca automática.',exclusions:['Confira data de compra, comprovante e sintomas.','Verifique fonte, vedação e conexão do cabo antes da assistência.','Siga o processo local. Danos por mau uso, líquidos ou reparo não autorizado ficam fora dos termos fornecidos.']}
 },
 fr:{
  intro:'Une solution filaire compacte pour la musique, le quotidien et les jeux.',storyEyebrow:'CINQ ARGUMENTS DE VENTE ESSENTIELS',masterAlt:'CHU III et câble détachable sur fond noir',heroAlt:'CHU III argentés près de feuilles de bambou',colorsAlt:'CHU III argentés et noirs',packageAlt:'Boîte, écouteurs CHU III, câble, embouts, pochette et documents',galleryIntro:'14 photographies originales, classées par produit, port et emballage. Chaque image peut être ouverte à sa résolution originale.',groups:['Produit','Port','Emballage'],original:'Photographie originale',galleryTitles:['Coques noires et argentées','Paire argentée avec guides autour des oreilles','Paire noire de face','Paire noire en biais','Paire argentée et câble complet','Paire noire et câble complet','Paire noire sur fond sombre','Paire argentée sur fond sombre','Paire argentée avec bambou','Paire argentée en lumière naturelle','Port vu de face','Port vu de profil','Contenu complet de la boîte','Emballage et accessoires en biais'],prices:['Prix de vente conseillés par région','Devise','Prix de vente conseillé'],reviewNotes:['Impressions d’écoute et rapport qualité-prix du CHU III.','Présentation de la nouvelle génération de la série CHU.','Comparaison du CHU III avec CHU II et d’autres intra-auriculaires d’entrée de gamme.'],
  stories:[
   ['Son et réglage acoustique','Transducteur dynamique de 10 mm · dôme Al-Mg','Commencer par un morceau familier.','Le transducteur dynamique de 10 mm utilise une membrane composite en alliage aluminium-magnésium. Le réglage acoustique a été développé avec le système de mesure B&K 5128. Laissez le client juger voix, graves et détails sur une musique connue.',[['Distinguer membrane et coque','Al-Mg désigne la membrane ; la coque extérieure est en alliage de zinc.'],['Comparer à volume similaire','L’étanchéité des embouts et le volume influencent l’écoute. Un matériau seul ne garantit pas un meilleur son.']],'Ajuster les embouts, commencer doucement et comparer un passage de voix et de graves connu à volume similaire.','« Écoutons un morceau que vous connaissez. Prêtez attention à la voix et aux graves, puis dites-moi ce que vous préférez. »','Transducteur dynamique de 10 mm · membrane composite Al-Mg · 16 Ω ±15 % (@1 kHz)','Coques argentées et noires ; le transducteur interne n’est pas visible sur cette photo.'],
   ['Fabrication et confort','Coque en zinc · câble autour de l’oreille','Des coques compactes, un confort à essayer.','Les coques compactes en alliage de zinc existent en noir et argent. Le câble passe autour de l’oreille ; les embouts S/M/L permettent d’ajuster le maintien. Une bonne étanchéité favorise les graves et l’isolation passive. Le confort reste personnel.',[['Choisir les embouts en premier','Essayer plusieurs tailles sans forcer une insertion profonde. Une mauvaise étanchéité peut réduire les graves.'],['Expliquer l’isolation','L’isolation passive n’est pas une réduction active du bruit. Ne pas promettre de résistance à la sueur sans indice confirmé.']],'Montrer les deux finitions, vérifier L/R, placer le câble autour de l’oreille et faire essayer deux tailles d’embouts.','« Essayez d’abord le maintien. Les bons embouts doivent être confortables et garder un son régulier. »','Alliage de zinc · noir / argent · embouts S/M/L','Exemple de port autour de l’oreille ; vérifier le confort et le maintien sur chaque personne.'],
   ['Connexion et utilisation','Audio 3,5 mm · aucune recharge des écouteurs','Vérifier la prise, puis écouter.','Le câble standard possède une fiche stéréo de 3,5 mm pour sortie casque. Un téléphone sans cette prise nécessite un adaptateur audio compatible. Les écouteurs n’ont pas besoin de recharge et évitent l’étape de transmission Bluetooth.',[['Vérifier la source','L’adaptateur USB-C ou Lightning doit prendre en charge la sortie audio de l’appareil concerné. Des écouteurs analogiques ne nécessitent pas d’appairage Bluetooth.'],['Bien expliquer les jeux','L’application, le jeu, l’adaptateur et l’appareil peuvent encore ajouter du retard. Ne pas promettre une latence totale nulle ni de meilleurs résultats.']],'Vérifier appareil et sortie, baisser le volume, brancher fiche ou adaptateur, puis tester musique et vidéo.','« Ces écouteurs n’ont pas besoin de recharge. Vérifions d’abord la connexion audio de votre téléphone. »','Stéréo 3,5 mm · 16 Ω ±15 % · 118 dB/Vrms (@1 kHz)','Paire argentée complète avec câble standard et fiche de 3,5 mm.'],
   ['Choix de câbles','Connexion détachable 2 broches de 0,78 mm','Adapter le câble à ses besoins.','La connexion à 2 broches de 0,78 mm permet un câble de remplacement compatible. Un câble avec micro, un câble symétrique ou un adaptateur sans fil sont des accessoires optionnels, pas des fonctions intégrées. Vérifier le connecteur et la source.',[['Brancher avec précaution','Vérifier L/R, orientation et polarité des broches selon les notices des écouteurs et du câble. Tenir le corps du connecteur, aligner les broches, sans tirer sur le fil ni forcer.'],['Vérifier toute la liaison','Un câble symétrique nécessite une sortie casque symétrique compatible. Le micro exige un câble et une voie d’entrée adaptés.']],'Montrer les connecteurs et repères L/R. Expliquer le câble et la sortie prévus avant de débrancher.','« Si vous avez ensuite besoin d’un micro ou d’un câble de remplacement, nous vérifierons une option compatible. »','2 broches de 0,78 mm · câble détachable · accessoires optionnels séparés','Écouteurs argentés avec connecteurs et sections autour des oreilles visibles.'],
   ['Entretien au quotidien','Embouts · canule · rangement du câble','Quelques gestes simples pour les garder prêts.','Garder embouts et ouverture de la canule propres et secs. Retirer les embouts pour vérifier, éviter de pousser saletés ou liquide à l’intérieur et ranger le câble sans le serrer dans la pochette. Confirmer la méthode de service avant de retirer un filtre.',[['Nettoyer délicatement','Utiliser un outil doux et sec autour de l’ouverture. Ne pas percer la grille ni démonter la coque.'],['Chercher la cause en premier','Si le son est faible ou déséquilibré, vérifier étanchéité, obstruction visible, branchement du câble et autre source avant le service.']],'Montrer le retrait de l’embout sans toucher la grille, examiner l’ouverture et ranger le câble sans serrer.','« Si un côté devient plus faible, vérifiez d’abord le maintien et les obstructions visibles. Si cela persiste, nous vous aiderons pour le service. »','Nettoyage à sec · aucun liquide dans la canule · câble compatible remplaçable','Écouteurs, embouts et pochette sur la photo originale du contenu de la boîte.']
  ],comparisons:[['Pour quel public ?','« Je cherche mes premiers écouteurs filaires. »','Une option compacte pour musique, bureau et jeux avec une sortie casque adaptée. Essayer le port et le passage du câble ; un adaptateur peut être nécessaire sur téléphone.','Connexion 3,5 mm · câble détachable'],['Face au Bluetooth','« Pourquoi choisir un câble ? »','CHU III ne nécessite ni recharge ni appairage et évite la transmission Bluetooth. Bluetooth offre plus de liberté de mouvement et parfois ANC ou appels. Choisir selon les habitudes.','Usage filaire et liberté sans fil'],['Face aux modèles ouverts','« Je dois entendre mon environnement. »','CHU III ferme le conduit avec des embouts pour une isolation passive. Les modèles ouverts le laissent libre et peuvent convenir à une perception continue de l’environnement. Comparer le port et le lieu réels.','Besoins différents de port et d’isolation'],['Face aux casques circum-auriculaires','« Je veux quelque chose de facile à transporter. »','CHU III prend peu de place mais utilise des embouts dans le conduit. Les casques évitent ce contact, mais sont plus volumineux. Choisir selon le confort sans attribuer systématiquement un meilleur son à un format.','Encombrement et préférence de port']],
  support:{contents:['Écouteurs CHU III','Câble standard de 3,5 mm','Pochette de rangement','Embouts S/M/L','Carte de conseils de port','Manuel d’utilisation','Certificat de conformité'],packageNote:'Photographie originale du contenu standard. Câbles optionnels et adaptateurs pour téléphone non inclus.',periods:[['Écouteurs CHU III','1 an'],['Accessoires fournis','90 jours']],policy:'La prise en charge des défauts de fonctionnement non causés par un mauvais usage dépend de la région d’achat et des conditions du distributeur local. La garantie ne signifie pas un remplacement automatique.',exclusions:['Vérifier la date d’achat, le justificatif et les symptômes.','Vérifier source, étanchéité et connexion du câble avant le service.','Suivre la procédure locale. Les dommages dus au mauvais usage, aux liquides ou à une réparation non autorisée sont exclus des conditions fournies.']}
 }
});
Object.assign(window.CHU3_COPY, {
 it:{
  intro:'Una soluzione compatta con cavo per musica, ascolto quotidiano e giochi.',storyEyebrow:'CINQUE ARGOMENTI CHIAVE DI VENDITA',masterAlt:'CHU III con cavo rimovibile su sfondo nero',heroAlt:'CHU III argentati accanto a foglie di bambù',colorsAlt:'CHU III nelle finiture argento e nero',packageAlt:'Scatola, auricolari CHU III, cavo, gommini, custodia e documenti',galleryIntro:'14 fotografie originali, suddivise in prodotto, indosso e confezione. Apri ogni immagine alla risoluzione originale.',groups:['Prodotto','Indosso','Confezione'],original:'Fotografia originale',galleryTitles:['Scocche nere e argentate','Coppia argentata con guide sopra l’orecchio','Coppia nera frontale','Coppia nera in prospettiva','Coppia argentata e cavo completo','Coppia nera e cavo completo','Coppia nera su sfondo scuro','Coppia argentata su sfondo scuro','Coppia argentata con bambù','Coppia argentata alla luce naturale','Indosso, vista frontale','Indosso, vista laterale','Contenuto completo della confezione','Confezione e accessori in prospettiva'],prices:['Prezzi al pubblico consigliati per regione','Valuta','Prezzo al pubblico consigliato'],reviewNotes:['Impressioni d’ascolto e rapporto qualità-prezzo di CHU III.','Uno sguardo alla nuova generazione della serie CHU.','Confronto fra CHU III, CHU II e altri IEM di fascia iniziale.'],
  stories:[
   ['Suono e taratura','Driver dinamico da 10 mm · cupola Al-Mg','Inizia con un brano familiare.','Il driver dinamico da 10 mm usa un diaframma composito in lega di alluminio e magnesio. La taratura acustica è stata sviluppata con il sistema di misura B&K 5128. Lascia valutare voci, bassi e dettagli con musica conosciuta.',[['Distingui diaframma e scocca','Al-Mg indica il diaframma; la scocca esterna è in lega di zinco.'],['Confronta a volume simile','Tenuta dei gommini e volume influenzano l’ascolto. Un materiale da solo non garantisce un suono migliore.']],'Scegli i gommini, parti a basso volume e confronta un passaggio conosciuto di voce e bassi a volume simile.','«Proviamo un brano che conosci. Ascolta voce e bassi, poi dimmi cosa preferisci.»','Driver dinamico da 10 mm · diaframma composito Al-Mg · 16 Ω ±15% (@1 kHz)','Scocche argentate e nere; il driver interno non è esposto nella fotografia.'],
   ['Costruzione e vestibilità','Scocca in zinco · cavo sopra l’orecchio','Scocche piccole, comfort da provare.','Le scocche compatte in lega di zinco sono disponibili in nero e argento. Il cavo passa sopra l’orecchio; i gommini S/M/L aiutano a regolare la tenuta. Una buona tenuta favorisce bassi e isolamento passivo. Il comfort varia da persona a persona.',[['Scegli prima il gommino','Prova diverse misure senza forzare un inserimento profondo. Una tenuta insufficiente può ridurre i bassi.'],['Spiega l’isolamento','L’isolamento passivo non è cancellazione attiva. Senza una classificazione confermata, non promettere resistenza al sudore.']],'Mostra entrambe le finiture, controlla L/R, passa il cavo sopra l’orecchio e fai provare due misure.','«Prova prima la vestibilità. I gommini giusti dovrebbero essere comodi e mantenere il suono uniforme.»','Lega di zinco · nero / argento · gommini S/M/L','Esempio di indosso con cavo sopra l’orecchio; verifica comfort e tenuta sulla persona.'],
   ['Connessione e facilità d’uso','Audio da 3,5 mm · auricolari senza ricarica','Controlla la presa, poi ascolta.','Il cavo standard ha uno spinotto stereo da 3,5 mm per uscita cuffie. I telefoni senza questa presa richiedono un adattatore audio compatibile. Gli auricolari non richiedono ricarica ed evitano il passaggio di trasmissione Bluetooth.',[['Verifica la sorgente','L’adattatore USB-C o Lightning deve supportare l’uscita audio sul dispositivo concreto. Gli auricolari analogici non richiedono abbinamento Bluetooth.'],['Descrivi correttamente i giochi','App, gioco, adattatore e dispositivo possono ancora aggiungere ritardo. Non promettere latenza totale zero o risultati migliori.']],'Controlla dispositivo e uscita, abbassa il volume, collega spinotto o adattatore e prova musica e video.','«Questi auricolari non richiedono ricarica. Controlliamo prima la connessione audio del telefono.»','Stereo da 3,5 mm · 16 Ω ±15% · 118 dB/Vrms (@1 kHz)','Coppia argentata completa con cavo standard e spinotto da 3,5 mm.'],
   ['Opzioni di cavo','Connettore rimovibile a 2 pin da 0,78 mm','Cambia cavo quando cambiano le esigenze.','Il connettore a 2 pin da 0,78 mm permette un cavo sostitutivo compatibile. Cavo con microfono, cavo bilanciato e adattatore wireless sono accessori opzionali, non funzioni integrate. Verifica connettore e sorgente.',[['Collega con attenzione','Verifica L/R, orientamento e polarità dei pin seguendo le istruzioni di auricolari e cavo. Tieni il corpo del connettore, allinea i pin e non tirare il filo né forzare.'],['Verifica l’intero collegamento','Un cavo bilanciato richiede un’uscita cuffie bilanciata compatibile. Il microfono necessita di cavo e percorso d’ingresso adeguati.']],'Indica connettori e segni L/R. Spiega cavo e uscita desiderati prima di scollegare.','«Se in seguito servirà un microfono o un cavo sostitutivo, possiamo verificare un’opzione compatibile.»','2 pin da 0,78 mm · cavo rimovibile · accessori opzionali separati','Auricolari argentati con connettori e sezioni sopra l’orecchio visibili.'],
   ['Cura e manutenzione','Gommini · condotto · cavo','Semplici abitudini per l’uso quotidiano.','Mantieni puliti e asciutti gommini e apertura del condotto. Togli i gommini per controllare, non spingere sporco o liquidi all’interno e riponi il cavo allentato nella custodia. Conferma la procedura di assistenza prima di rimuovere un filtro.',[['Pulisci delicatamente','Usa uno strumento morbido e asciutto intorno all’apertura. Non perforare la rete né smontare la scocca.'],['Cerca prima la causa','Se il suono è debole o sbilanciato, controlla tenuta, ostruzioni visibili, innesto del cavo e un’altra sorgente prima dell’assistenza.']],'Mostra come togliere il gommino senza toccare la rete, controllare l’apertura e riporre il cavo senza stringerlo.','«Se un lato suona più piano, controlla prima la tenuta e le ostruzioni visibili. Se continua, ti aiutiamo con l’assistenza.»','Pulizia a secco · nessun liquido nel condotto · cavo compatibile sostituibile','Auricolari, gommini e custodia nella fotografia originale della confezione.']
  ],comparisons:[['A chi si rivolge','«Cerco i miei primi auricolari con cavo.»','Una scelta compatta per musica, scrivania e giochi con uscita cuffie adeguata. Prova vestibilità e percorso del cavo; il telefono potrebbe richiedere un adattatore.','Connessione da 3,5 mm · cavo rimovibile'],['Rispetto al Bluetooth','«Perché scegliere un cavo?»','CHU III non richiede ricarica o abbinamento ed evita la trasmissione Bluetooth. Il Bluetooth offre più libertà di movimento e può includere ANC o chiamate. Scegli secondo la routine.','Uso con cavo e libertà senza fili'],['Rispetto ai modelli aperti','«Devo sentire l’ambiente.»','CHU III sigilla il canale con gommini per isolamento passivo. I modelli aperti lo lasciano libero e possono favorire l’ascolto continuo dell’ambiente. Confronta vestibilità e luogo reali.','Esigenze diverse di indosso e isolamento'],['Rispetto alle cuffie circumaurali','«Voglio qualcosa di facile da portare.»','CHU III occupa poco spazio ma richiede gommini nel canale. Le cuffie evitano quel tipo di contatto ma sono più grandi. Decidi in base al comfort senza presumere che un formato suoni sempre meglio.','Ingombro ridotto e preferenze di indosso']],
  support:{contents:['Auricolari CHU III','Cavo standard da 3,5 mm','Custodia morbida','Gommini S/M/L','Scheda per il corretto indosso','Manuale utente','Certificato di conformità'],packageNote:'Fotografia originale della confezione standard. Cavi opzionali e adattatori per telefono non inclusi.',periods:[['Auricolari CHU III','1 anno'],['Accessori inclusi','90 giorni']],policy:'La copertura dei difetti di funzionamento non dovuti a uso improprio segue la regione di acquisto e le condizioni del canale locale. L’assistenza in garanzia non implica sostituzione automatica.',exclusions:['Verifica data d’acquisto, ricevuta e sintomi.','Controlla sorgente, tenuta e collegamento del cavo prima dell’assistenza.','Segui la procedura locale. Danni da uso improprio, liquidi o riparazioni non autorizzate sono esclusi dalle condizioni fornite.']}
 },
 ru:{
  intro:'Компактные проводные наушники для музыки, повседневного прослушивания и игр.',storyEyebrow:'ПЯТЬ ГЛАВНЫХ АРГУМЕНТОВ ДЛЯ ПРОДАЖИ',masterAlt:'Наушники CHU III и съёмный кабель на чёрном фоне',heroAlt:'Серебристые CHU III рядом с листьями бамбука',colorsAlt:'CHU III в серебристом и чёрном цветах',packageAlt:'Коробка, наушники CHU III, кабель, насадки, мешочек и документы',galleryIntro:'14 оригинальных фотографий: внешний вид, посадка и упаковка. Любое изображение можно открыть в исходном разрешении.',groups:['Внешний вид','Посадка','Упаковка'],original:'Оригинальная фотография',galleryTitles:['Чёрные и серебристые корпуса','Серебристая пара с заушинами','Чёрная пара спереди','Чёрная пара под углом','Серебристая пара с полным кабелем','Чёрная пара с полным кабелем','Чёрная пара на тёмном фоне','Серебристая пара на тёмном фоне','Серебристая пара с бамбуком','Серебристая пара при естественном свете','Посадка спереди','Посадка сбоку','Полный комплект поставки','Упаковка и аксессуары под углом'],prices:['Рекомендованные розничные цены по регионам','Валюта','Рекомендованная розничная цена'],reviewNotes:['Впечатления от звучания CHU III и соотношения цены и качества.','Обзор нового поколения серии CHU.','Сравнение CHU III с CHU II и другими начальными внутриканальными моделями.'],
  stories:[
   ['Звук и настройка','Динамический излучатель 10 мм · купол Al-Mg','Начните со знакомой песни.','Динамический излучатель 10 мм использует композитную диафрагму из алюминиево-магниевого сплава. Акустическая настройка разработана с измерительной системой B&K 5128. Предложите оценить вокал, бас и детали на знакомой музыке.',[['Диафрагма и корпус — разные детали','Al-Mg относится к диафрагме; внешний корпус выполнен из цинкового сплава.'],['Сравнивайте при близкой громкости','Герметичность посадки и громкость влияют на впечатление. Один материал сам по себе не гарантирует лучшего звука.']],'Подберите насадки, начните с малой громкости и сравните знакомый отрывок с вокалом и басом при близком уровне.','«Послушаем знакомую вам песню. Обратите внимание на вокал и бас и расскажите, что вам нравится».','Динамический излучатель 10 мм · композитная диафрагма Al-Mg · 16 Ω ±15% (@1 кГц)','Серебристые и чёрные корпуса; внутренний излучатель на фотографии не показан.'],
   ['Конструкция и посадка','Цинковый сплав · заушная укладка','Компактные корпуса, посадку стоит примерить.','Компактные корпуса из цинкового сплава доступны в чёрном и серебристом цветах. Кабель проходит за ухом, а насадки S/M/L помогают подобрать посадку. Хорошее уплотнение поддерживает бас и пассивную изоляцию; комфорт индивидуален.',[['Сначала подберите насадки','Попробуйте разные размеры без принудительной глубокой посадки. Неплотное прилегание может ослабить бас.'],['Объясняйте изоляцию точно','Пассивная изоляция не является активным шумоподавлением. Без подтверждённого класса защиты не обещайте стойкость к поту.']],'Покажите оба цвета, проверьте L/R, проведите кабель за ухом и предложите два размера насадок.','«Сначала примерьте. Подходящие насадки должны быть удобными и обеспечивать стабильное звучание».','Цинковый сплав · чёрный / серебристый · насадки S/M/L','Пример заушной укладки; комфорт и прилегание проверяются индивидуально.'],
   ['Подключение и работа с источником','Аудио 3,5 мм · без зарядки наушников','Проверьте разъём и включите музыку.','Штатный кабель имеет стереоштекер 3,5 мм для выхода на наушники. Телефону без такого разъёма нужен совместимый аудиоадаптер. Наушники не требуют зарядки и обходятся без этапа передачи по Bluetooth.',[['Проверьте источник','Адаптер USB-C или Lightning должен поддерживать вывод звука на конкретном устройстве. Аналоговым наушникам не нужно сопряжение Bluetooth.'],['Точно описывайте игры','Приложение, игра, адаптер и устройство всё ещё могут добавлять задержку. Не обещайте нулевую общую задержку или улучшение результатов.']],'Проверьте устройство и выход, уменьшите громкость, подключите штекер или адаптер и протестируйте музыку и видео.','«Эти наушники не нужно заряжать. Сначала проверим аудиоподключение вашего телефона».','Стерео 3,5 мм · 16 Ω ±15% · 118 dB/Vrms (@1 кГц)','Серебристая пара со штатным кабелем и штекером 3,5 мм целиком.'],
   ['Варианты кабеля','Съёмное соединение 2 pin 0,78 мм','Кабель можно подобрать под новые задачи.','Разъём 2 pin 0,78 мм позволяет заменить кабель совместимым. Кабель с микрофоном, балансный кабель и беспроводной адаптер — отдельные аксессуары, а не встроенные функции. Проверяйте разъём и совместимость источника.',[['Подключайте аккуратно','Проверьте L/R, ориентацию и полярность контактов по инструкциям к наушникам и кабелю. Держите корпус разъёма, выравнивайте контакты, не тяните провод и не применяйте силу.'],['Проверяйте всю цепочку','Балансный кабель требует совместимого балансного выхода на наушники. Микрофону нужны подходящий кабель и путь входного сигнала.']],'Покажите разъёмы и метки L/R. Перед отсоединением объясните выбор кабеля и выхода.','«Если позже понадобится микрофон или запасной кабель, мы проверим совместимый вариант».','2 pin 0,78 мм · съёмный кабель · дополнительные аксессуары отдельно','Серебристые наушники с видимыми разъёмами и заушными участками кабеля.'],
   ['Уход и обслуживание','Насадки · звуковод · хранение кабеля','Простые привычки на каждый день.','Держите насадки и отверстие звуковода чистыми и сухими. Для осмотра снимите насадки, не проталкивайте грязь или жидкость внутрь и свободно укладывайте кабель в мешочек. Перед снятием фильтра уточните допустимый способ обслуживания.',[['Очищайте бережно','Используйте мягкий сухой инструмент вокруг отверстия. Не прокалывайте сетку и не разбирайте корпус.'],['Сначала найдите причину','При слабом или неравномерном звуке проверьте прилегание, видимый засор, соединение кабеля и другой источник до обращения в сервис.']],'Покажите снятие насадки без касания сетки, осмотр отверстия и свободную укладку кабеля.','«Если одна сторона стала тише, сначала проверьте посадку и видимый засор. Если проблема остаётся, поможем с обращением в сервис».','Сухая очистка · без жидкости в звуководе · совместимый сменный кабель','Наушники, насадки и мешочек на оригинальной фотографии комплекта.']
  ],comparisons:[['Кому подходят','«Хочу первые проводные наушники».','Компактный вариант для музыки, рабочего стола и игр при наличии подходящего выхода. Примерьте посадку и укладку кабеля; телефону может потребоваться адаптер.','Разъём 3,5 мм · съёмный кабель'],['В сравнении с Bluetooth','«Почему стоит выбрать кабель?»','CHU III не требует зарядки и сопряжения, исключает передачу Bluetooth. Bluetooth даёт больше свободы движений, а некоторые модели предлагают ANC и звонки. Выбирайте под свой распорядок.','Проводное использование и свобода без проводов'],['В сравнении с открытыми моделями','«Мне нужно слышать окружающих».','Насадки CHU III закрывают канал для пассивной изоляции. Открытые модели оставляют его свободным и могут подойти для постоянного восприятия окружения. Сравните реальную посадку и условия.','Разные требования к посадке и изоляции'],['В сравнении с полноразмерными','«Хочу что-то удобное в дороге».','CHU III занимает мало места, но требует насадок в слуховом канале. Полноразмерные наушники обходятся без них, однако крупнее. Выбирайте по комфорту, не считая один формат всегда лучшим по звуку.','Компактность и предпочтения в посадке']],
  support:{contents:['Наушники CHU III','Штатный кабель 3,5 мм','Мешочек для хранения','Насадки S/M/L','Карточка с инструкцией по посадке','Руководство пользователя','Сертификат соответствия'],packageNote:'Оригинальная фотография стандартного комплекта. Дополнительные кабели и адаптеры для телефона не входят в комплект.',periods:[['Наушники CHU III','1 год'],['Комплектные аксессуары','90 дней']],policy:'Обслуживание неисправностей, не вызванных неправильным использованием, зависит от региона покупки и условий местного продавца. Гарантия не означает автоматическую замену.',exclusions:['Проверьте дату покупки, документ и симптомы неисправности.','До обращения в сервис проверьте источник, посадку насадок и подключение кабеля.','Следуйте местной процедуре. Повреждения из-за неправильного использования, жидкости или неавторизованного ремонта исключены предоставленными условиями.']}
 }
});
